#!/bin/sh

#  Frank Lübeck
#  $Id$

# this script is for forcing the re-creation of the web pages (e.g., after
# changes of the non-dynamic text

#####  edit here, give your GAP executable, and  mail address(es) for
#####  sending the log and error files as notification
#export GAP=gap
export GAP=g4l
#####
#####

$GAP PackageInfoUtils.g <<EOF
ReadAllPackageInfos("../pkg");
UpdatePackageWebPages("../web");
EOF

