#!/usr/bin/env perl
$version = `cat VERSION`;
chomp $version;
system( "make distclean; cp README ../README.anupq; ".
        "rm -f ../anupq-$version.zoo" );
chdir "..";
$prune = "zoo|make_|replace|[._]cvs|[.]tsk|[.]bbl|[.]aux".
         "|[.][ib]lg|[.]log|[.]ind|[.]idx|[.]swp|[.-]bak|~".
         "|[.]tst-new|magma|src/malloc.h|anupq4r2cpt|anupq/TEST|doc/test".
         "|anupq/isom|anupq/gap";
# Create new .zoo file
system( "find anupq -path '*/CVS' -prune -o -print | egrep -v '$prune' |".
        "zoo ahI anupq-$version.zoo" );
@files = `find anupq -path '*/CVS' -prune -o -print | egrep -v '$prune'`;
# Mark some files as text files
for $file ( @files ) {
  chomp $file;
  if ($file =~ 
       /[.](txt|g(|[id])|[ch]|htm|tex|bib|lab|toc|six|tst|pga|out|sp|mst)$/ ||
      $file =~ /(VERSION|README|Makefile|testPq|configure)/ ||
      $file =~ /(standalone\/(TEST|examples|isom)|examples)\//) {
    system( "(echo '!TEXT!'; echo '/END') | zoo c anupq-$version.zoo $file" );
  }
}
