#!/bin/sh
# this program can be used to build automatically a list of package manuals
# on the web. Eventually it should be extended to fetch a more current
# manual version if available as well.
# usage: htmpkgman status pkglistfile
# status is C A D S,   X gives all

echo "HTML documentation for $1 packages from $2"

# produce a getting file
awk -v status=$1 'BEGIN{name="";sta="";ver="";readme="";desc="";\
  htmdoc="";FS="/";cnt=0;\
  print "<TABLE>";\
  print "<TR><TD>Package</TD><TD>Description</TD></TR>";}\
{ if (substr($0,1,4)=="PKG:") {\
    name="";sta="";ver="";readme="";\
    name=substr($0,6);\
  }\
  if (substr($0,1,7)=="STATUS:") {\
    sta=substr($0,9,1);\
  }\
  if (substr($0,1,5)=="DESC:") {\
    desc=substr($0,7);\
  }\
  if (substr($0,1,7)=="HTMDOC:") {\
    htmdoc=substr($0,9);\
    if ((sta==status)||(status=="X")) {\
      print "<TR><TD><A HREF=\"pkg/" name "/" htmdoc "\">" name "</A></TD><TD>" desc "</TD></TR>";\
    }\
  }\
}\
END{print "</TABLE>"; }' $2 >pkg.tbl

echo "created pkg.tbl"

