#!/bin/sh
#########################################################################
##
#W  make_doc        make ACE Package documentation       Alexander Hulpke
#W                                                            Greg Gamble
##
#H  $Id: make_doc,v 1.7 2003/12/22 17:25:37 gap Exp $
##
##  This shell script uses TeX, BibTeX and MakeIndex to  build  the  .dvi
##  PostScript (commented  out), PDF and HTML (provided you have tth  and
##  etc/convert.pl) documentation for the ACE Package.
##

echo "TeXing documentation"
# TeX the manual and build its bibliography
tex manual;bibtex manual
# TeX the manual again to incorporate the ToC ... and build the index
tex manual; ../../../doc/manualindex manual
# Finally TeX the manual again to get cross-references right
tex manual
# Create the PDF version of the manual
pdftex manual
# Create the PostScript version (uncomment next line, if needed)
#dvips -D300 manual -o

# The HTML version of the manual
mkdir -p ../htm
echo "Creating HTML documentation"
../../../etc/convert.pl -t -c -n ACE . ../htm

#########################################################################
##
#E
