#!/bin/sh

PKGZOO=carat-2.0.1.zoo

# remove old archive
rm -f $PKGZOO

# goto <gaproot>/pkg
cd ../..

# make the package archive

# first the binary files
echo "!BINARY!" | zoo ach carat/etc/$PKGZOO carat/doc/manual.dvi
echo "!BINARY!" | zoo ach carat/etc/$PKGZOO carat/doc/manual.pdf
echo "!BINARY!" | zoo ach carat/etc/$PKGZOO carat/carat-2.0.tar.gz

# then the text files
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/doc/manual.tex
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/doc/manual.bbl
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/doc/manual.six
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/doc/manual.lab
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/doc/manual.toc
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/doc/manual.mst
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/doc/manual.ps
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/doc/carat.tex
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/doc/introduction.tex
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/doc/installation.tex
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/doc/make_doc
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/PackageInfo.g
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/init.g
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/read.g
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/README
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/Changelog
for file in carat/gap/*.g[di] ; do
  echo "!TEXT!" | zoo ach carat/etc/$PKGZOO $file
done
for file in carat/htm/*.htm ; do
  echo "!TEXT!" | zoo ach carat/etc/$PKGZOO $file
done

# check the results
cd carat/etc
zoo -list $PKGZOO
