# Make sure to include any M4 files needed by configure.ac here
m4_include([cnf/m4/ax_check_library.m4])
m4_include([cnf/m4/ax_gcc_func_attribute.m4])
m4_include([cnf/m4/ax_pthread.m4])
m4_include([cnf/m4/gap.m4])
m4_include([cnf/m4/libtool.m4])
m4_include([cnf/m4/ltoptions.m4])
m4_include([cnf/m4/ltsugar.m4])
m4_include([cnf/m4/ltversion.m4])
m4_include([cnf/m4/lt~obsolete.m4])
