# GAP Development Environment
#
# This conda environment provides the necessary tools and libraries for
# developing and testing GAP on Windows.
#
# Usage:
#   conda env create -f environment-win.yml
#   conda activate gap-dev

name: gap-dev
channels:
  - conda-forge
dependencies:
  # Core development tools
  - make
  - pkg-config
  - m2-autoconf
  - m2-libtool
  - m2-m4
  - m2-grep
  - m2-sed

  # C/C++ compiler and build tools
  - m2w64-gcc
  - ccache

  # Required libraries
  - m2w64-gmp # GNU Multiple Precision Arithmetic Library
  - m2w64-zlib # Compression library
