# GAP Development Environment
#
# This conda environment provides the necessary tools and libraries for
# developing and testing GAP (Groups, Algorithms, Programming).
#
# Usage:
#   conda env create -f environment.yml
#   conda activate gap-dev
#
# For Windows, you have to install MinGW-w64 separately
# (see README.md for instructions).

name: gap-dev
channels:
  - conda-forge
dependencies:
  # Core development tools
  - make
  - pkg-config
  # - autoconf # not available on Windows
  # - automake # not available on Windows
  # - libtool # not available on Windows

  # C/C++ compiler and build tools
  # - compilers (not available on Windows)
  - ccache

  # Required libraries
  - gmp # GNU Multiple Precision Arithmetic Library
  - zlib # Compression library
  #- readline # Command line editing library (not available on Windows)

