#!/bin/sh
if [ "x$GAPPACKAGES" = "x" ] ; then
    export GAPPACKAGES="io orb edim Browse"
    echo Taking \"$GAPPACKAGES\" as list of packages.
    echo Please set the GAPPACKAGES environment variable to overwrite.
    echo Starting in 5 seconds...
    sleep 5
fi
for p in $GAPPACKAGES ; do
    cd pkg/$p
    ./configure
    make clean
    ./configure
    make
    cd ../..
done
