This distribution of SISYPHOS can be used as a drop in replacement for the
older version shipped with GAP 3.4.x. 

Just unpack the archive in the directory GAPDIR/pkg/sisyphos, cd to the
subdirectory 'src' and follow the usual configuration/compiling
procedure. Note, that you must not specify '--with-readline' as option for
'configure' if you build SISYPHOS to be used as GAP shared package. 

After a successful compilation copy the executable 'sis' to the directory
GAPDIR/pkg/sisyphos/bin. 

