#!/bin/csh
#############################################################################
##
##  $Id: doit,v 1.2 2003/12/19 17:47:50 gap Exp $


./setvar
./checkout
./makedoc
./completionfiles
./fixpermissions
./zooandtag
./winbin
./zooandtagdata


