#!/bin/csh
#############################################################################
##
##  $Id$


./setvar
./checkout
./fixpermissions
./makedoc
./completionfiles
./zooandtag
./winbin
./zooandtagdata


