#!/bin/sh

#############################################################################
##
##  $Id: findstrangepermissions,v 1.1 2004/03/10 21:58:05 gap Exp $ Frank Lübeck
##  
##  Small utility for discovering potentially problematic file permissions.
##  Needs (GNU?)  'find'.
##  

echo "Directories not having 755 permissions:"
find . -type d -printf "%m %p\n" | grep -v "^755"

echo
echo "Files not having 644 or 755 permissions:"
find . -type f -printf "%m %p\n" | grep -v "^644" | grep -v "^755"

echo
echo "Files with 755 permission, not recognized as executables by 'file':"
find . -type f -perm 755 -exec file \{\} \; |grep -v executable

