#!/bin/sh
#############################################################################
##
##  $Id$

if [ ${DISTROOT}X==X ]; then
  echo 'Loading environment settings'
  source ./setvar
fi

line='cd '${DISTROOT}'/'${DISTNAME}'/doc'
echo $line
$line 

# build the documentation
line='./make_doc > ../../make_doc.log 2> ../../make_doc.error'
echo $line
rm -f ../../make_doc.log ../../make_doc.error
./make_doc > ../../make_doc.log 2> ../../make_doc.error
echo 'See the files '${DISTROOT}'/make_doc.log and '${DISTROOT}'/make_doc.error for possible problems.'

# this is the mozilla version. Build IE version
cp -r htm htmmoz
(cd htm;make clean;make ieversion >> ../../../make_doc.log 2>> ../../../make_doc.error)
mv htm htmie
mv htmmoz htm

# fetch the `INSTALL' files from the manual
grep -v "^%" ref/README.tex > ../README
chmod go+r ../README

# grep for "full" and "undef" in manual.log files and append to main log
echo "" >> ../../make_doc.log
echo "" >> ../../make_doc.log
echo "Over/underfull boxes and undefined things in manuals ..." >> ../../make_doc.log
grep "\(full\|undef\)" */manual.log >> ../../make_doc.log

exit 0

