#!/bin/sh
#############################################################################
##
##  $Id$

# where to put the temporary export tree and archives
export DISTROOT=/scratch/gap4dist

# the cvs repository (login once, before using these scripts) 
export CVSROOT=":pserver:gap@cvs-gap.dcs.st-and.ac.uk:/gap/CVS"

# the version to wrap, "-D now" for current, for the release first tag
# all files when the status of a release candidate is reached, say:
#      cvs tag -b -D now GAP4r4
# (the -b flag created a CVS branch such that (bugfix) changes can be
# applied independently of the changes in the main branch.)
export GAPCVSVERSION="-D now"
#export GAPCVSVERSION="-r GAP4r4"

# version to wrap
export VERSION="4"
FULLVERSION="4.0"

# related names
export RBVERSION="4r$VERSION"
export DISTNAME="gap$RBVERSION"

export PKGLOC="ftp://beteigeuze.math.rwth-aachen.de/pub/gap/gap4/tar.gz/packages-\*.tar.gz"

#-----------------------------------------------------------------------------
# everything below should be system independent.

# binary directory
export BINDIR=`pwd`

# what is *this moment*
export DATE=`date +"%d-%b-%Y"`


echo "Environment set for creating Version GAP 4."${FULLVERSION}

