#!/bin/sh
#############################################################################
##
##  $Id$

# where to put the temporary export tree and archives
export DISTROOT=/scratch/gap4dist/4411/wrap

# the cvs repository (login once, before using these scripts) 
export CVSROOT="gap@cvs-gap.dcs.st-and.ac.uk:/gap/CVS"

# the version to wrap, "-D now" for current, for the release first tag
# all files when the status of a release candidate is reached, say:
#      cvs tag -b -D now GAP4r4
# (the -b flag created a CVS branch such that (bugfix) changes can be
# applied independently of the changes in the main branch.)
#export GAPCVSVERSION="-D now"
export GAPCVSVERSION="-r GAP4R4"

# version to wrap
export VERSION="4"
export FULLVERSION="$VERSION.11"

# directory name
export DISTNAME="gap4r$VERSION"

# archive name
export RBVERSION="4r4p11"
export ARCHNAME="gap$RBVERSION"

# package archive URL
export PKGLOC="ftp://ftp.gap-system.org/pub/gap/gap4/tar.gz/packages-2008_11_26-00_04_UTC.tar.gz"

# version of tomlib to include
export TOMLIBVER="1r1p4"

#-----------------------------------------------------------------------------
# everything below should be system independent.

# binary directory
export BINDIR=`pwd`

# unset locale settings
export LANG="C"
export LC_ALL="C"

# what is *this moment*
export DATE=`date +"%d-%b-%Y"`

umask 022

echo "Environment set for creating Version GAP 4."${FULLVERSION}

