#!/bin/sh
#############################################################################
##

if [ ${DISTROOT}X==X ]; then
  echo 'Loading environment settings'
  source ./setvar
fi

TGZ=${DISTROOT}'/wincode.tgz'
BINTGZ=${DISTROOT}'/winbin.tgz'

if [ \! -f ${BINTGZ} ];  then
  echo "No archive "${BINTGZ}" found, packing source."
  cd ${DISTROOT}'/'${DISTNAME}
  tar zcf ${TGZ} src/* cnf/* configure "configure.in" \
          "Makefile.in" "sysinfo.in" gap.shi

  echo "Transfer the file:  "${TGZ}
  echo "to a PC with installed cygwin. Extract the file using"
  echo "      tar zxf wincode.tgz "
  echo "also install at least the packages IO, edim and Browse,"
  echo "then call"
  echo "     ./configure"
  echo "     make"
  echo "     cp bin/i686-pc-cygwin-gcc/gap.exe bin/gapw95.exe"
  echo "     cd bin/i686-pc-cygwin-gcc"
  echo '     ./gac -o gapw95p.exe \\'
  echo '           -p "-DIOSTATIC -DEDIVSTATIC -PNCURSESSTATIC" \\'
  echo '           -P "-lpanel -lncurses" ../../pkg/io/src/io.c \\'
  echo '           ../../pkg/edim/src/ediv.c ../../pkg/Browse/src/ncurses.c'
  echo "     strip gapw95p.exe"
  echo "     cp gapw95p.exe .."
  echo "     cd ../.."
  echo "     cp /bin/cygwin1.dll bin"
  echo "     cp /bin/cygncurses-8.dll bin"
  echo "     cp /bin/cygpanel-8.dll bin"
  echo "     cp /usr/bin/rxvt.exe bin"
  echo "     cp /usr/bin/regtool.exe bin"
  echo "     cp /bin/libW11.dll bin"
  echo "     tar zcf winbin.tgz bin/gapw95.exe bin/cygwin1.dll \\"
  echo "         bin/cygncurses-8.dll bin/cygpanel-8.dll bin/rxvt.exe \\"
  echo "         bin/libW11.dll bin/gapw95p.exe bin/regtool.exe"
  echo "Then copy the resulting winbin.tgz archive to"
  echo "     "${DISTROOT}"/winbin.tgz"
  echo "on this machine and leave by typing 'exit'."
  (cd ${DISTROOT};bash)
  echo "Thanks!"
fi
if [ \! -f ${BINTGZ} ];  then
  echo ${BINTGZ}" not found"
  exit 1
else
  echo "Found "${BINTGZ}
  echo "Adding it to main zoo archive."
  cd ${DISTROOT}'/'${DISTNAME}
  tar zxf ${BINTGZ}
  # these should be already in the repository
  if [ \! -x bin/gapw95.exe ];  then
     echo "PANIC: no executable has been created"
     exit 1
  fi
  cd ${DISTROOT}
  zooarchive=${ARCHNAME}.zoo
  if [ \! -f  ${DISTROOT}/${zooarchive} ];  then
     echo "PANIC: zoo archive to add to not yet created: "\
           ${DISTROOT}"/"${zooarchive}
     exit 1
  fi
  chmod 755 ${DISTNAME}/bin/gapw95.exe ${DISTNAME}/bin/cygwin1.dll \
            ${DISTNAME}/bin/gapw95p.exe ${DISTNAME}/bin/cygncurses-8.dll \
            ${DISTNAME}/bin/cygpanel-8.dll ${DISTNAME}/bin/libW11.dll \
            ${DISTNAME}/bin/rxvt.exe ${DISTNAME}/bin/regtool.exe \
            ${DISTNAME}/bin/gap.dll ${DISTNAME}/terminfo/* \
            ${DISTNAME}/bin/i686-pc-cygwin-gcc/gac \
            ${DISTNAME}/bin/i686-pc-cygwin-gcc/gap.dll \
            ${DISTNAME}/bin/i686-pc-cygwin-gcc/config.h \
            ${DISTNAME}/pkg/Browse/bin/i686-pc-cygwin-gcc/ncurses.so \
            ${DISTNAME}/pkg/io/bin/i686-pc-cygwin-gcc/io.so \
            ${DISTNAME}/pkg/edim/bin/i686-pc-cygwin-gcc/ediv.so
  (echo "!BINARY!"; echo "/end") | zoo ahc ${zooarchive} ${DISTNAME}/bin/gapw95.exe
  (echo "!BINARY!"; echo "/end") | zoo ahc ${zooarchive} ${DISTNAME}/bin/cygwin1.dll
  (echo "!BINARY!"; echo "/end") | zoo ahc ${zooarchive} ${DISTNAME}/bin/cygncurses-8.dll
  (echo "!BINARY!"; echo "/end") | zoo ahc ${zooarchive} ${DISTNAME}/bin/cygpanel-8.dll
  (echo "!BINARY!"; echo "/end") | zoo ahc ${zooarchive} ${DISTNAME}/bin/libW11.dll
  (echo "!BINARY!"; echo "/end") | zoo ahc ${zooarchive} ${DISTNAME}/bin/gap.dll
  (echo "!BINARY!"; echo "/end") | zoo ahc ${zooarchive} ${DISTNAME}/bin/gapw95p.exe
  (echo "!BINARY!"; echo "/end") | zoo ahc ${zooarchive} ${DISTNAME}/bin/regtool.exe
  (echo "!BINARY!"; echo "/end") | zoo ahc ${zooarchive} ${DISTNAME}/bin/i686-pc-cygwin-gcc/gap.dll
  (echo "!BINARY!"; echo "/end") | zoo ahc ${zooarchive} ${DISTNAME}/bin/i686-pc-cygwin-gcc/gac
  (echo "!BINARY!"; echo "/end") | zoo ahc ${zooarchive} ${DISTNAME}/bin/i686-pc-cygwin-gcc/config.h
  (echo "!BINARY!"; echo "/end") | zoo ahc ${zooarchive} ${DISTNAME}/terminfo/c/cygwin
  (echo "!BINARY!"; echo "/end") | zoo ahc ${zooarchive} ${DISTNAME}/terminfo/r/rxvt
  (echo "!BINARY!"; echo "/end") | zoo ahc ${zooarchive} ${DISTNAME}/terminfo/x/xterm
  (echo "!BINARY!"; echo "/end") | zoo ahc ${zooarchive} ${DISTNAME}/pkg/Browse/bin/i686-pc-cygwin-gcc/ncurses.so
  (echo "!BINARY!"; echo "/end") | zoo ahc ${zooarchive} ${DISTNAME}/pkg/io/bin/i686-pc-cygwin-gcc/io.so
  (echo "!BINARY!"; echo "/end") | zoo ahc ${zooarchive} ${DISTNAME}/pkg/edim/bin/i686-pc-cygwin-gcc/ediv.so
  echo "added Windows binary to zoo archive."
  exit 0
fi

