#!/bin/sh
#############################################################################
##
##  $Id$

if [ ${DISTROOT}X==X ]; then
  echo 'Loading environment settings'
  source ./setvar
fi

line='cd '${DISTROOT}
echo $line
$line 

pre=${DISTNAME}
zooarchive=${ARCHNAME}.zoo
rm -f $zooarchive

echo 'Adding and tagging text files to archive '${DISTROOT}/$zooarchive

find \
   $pre/README \
   $pre/descript* \
   $pre/{lib,grp,tst,src} \
   $pre/doc/{gapmacro.tex,manual.bib,manualindex,fullindex.tex} \
   $pre/doc/{ref,tut,ext,prg,new}/*.{tex,six,mst,lab,toc,ind} \
   $pre/doc/test/{mk}* \
   $pre/doc/test/README \
   $pre/doc/htm/*.htm \
   $pre/doc/htm/{ref,tut,ext,prg,new} \
   $pre/etc/{*vim*,emacs,GPL,xrmtcmd.c} \
   $pre/pkg/PKGDIR \
   $pre/bin/*.bat \
       -type f -exec sh -c \
       '(echo "!TEXT!"; echo "/end") |  zoo ahc '${zooarchive}' '{} ";"
             

find \
   $pre/{gap.shi,Makefile.in,sysinfo.in,configure*,gap.ini,cnf} \
   $pre/doc/{ref,tut,ext,prg,new}/*.{dvi,pdf} \
   $pre/doc/fullindex.{dvi,pdf} \
   $pre/bin/*.{exe,dll,bmp,pif} \
       -type f -exec sh -c \
       '(echo "!BINARY!"; echo "/end") |  zoo ahc '${zooarchive}' '{} ";"

zootools=tools${RBVERSION}.zoo
echo 'Packing '${DISTROOT}/$zootools
rm -f $zootools

find \
   $pre/doc/{allmanualsindex,gapmacro.tex,make_doc,mrabbrev.bib} \
   $pre/doc/{manualindex,htm/Makefile,htm/allhtmlindex,htm/onehtmlindex} \
   $pre/doc/{fullindex.mst,build/Makefile} \
   $pre/doc/build/config.* \
   $pre/doc/build/*.msk \
   $pre/etc/{buildman.pe,convert.pl,packpack,unzoo.c,README.tools} \
       -type f -exec sh -c \
       '(echo "!TEXT!"; echo "/end") |  zoo ahc '${zootools}' '{} ";"

htmie=htmie${RBVERSION}.zoo
echo 'Packing '${DISTROOT}/$htmie
rm -f $htmie

find \
   $pre/doc/htmie/*.htm \
   $pre/doc/htmie/{ref,tut,ext,prg,new} \
       -type f -exec sh -c \
       '(echo "!TEXT!"; echo "/end") |  zoo ahc '${htmie}' '{} ";"

exit 0

