#!/bin/sh

GAPROOT=${1:-../../..}
GAP=${2:-$GAPROOT/bin/gap.sh}

$GAP -A -q -T <<GAPDOC_SCRIPT
LoadPackage("gapdoc");;
MakeGAPDocDoc( ".", "main", [ "../PackageInfo.g" ], "polenta", "$GAPROOT", "MathJax" );;
CopyHTMLStyleFiles(".");
GAPDOC_SCRIPT
