language: c
matrix:
  include:
    - os: linux
      env: TEST_SUITE=testtravis
      compiler: gcc
    - os: osx
      env: TEST_SUITE=testtravis
      compiler: clang
    - os: linux
      env: TEST_SUITE=testinstall
      compiler: gcc
    - os: linux
      env: TEST_SUITE=testbugfix
      compiler: gcc

# Change this to your needs
addons:
  apt_packages:
  - libgmp3-dev
  - texlive-latex-base
  - texlive-latex-recommended
  - texlive-latex-extra
  - texlive-extra-utils
  - texlive-fonts-recommended
  - texlive-fonts-extra
script:
  - git clone --depth=50 https://github.com/gap-system/ward extern/ward
  - ./make.hpc WARD="extern/ward" GMP=system ZMQ=no
  - cd pkg
  - wget ftp://ftp.gap-system.org/pub/gap/gap47/tar.gz/packages/autpgrp-1.5.tar.gz
  - wget ftp://ftp.gap-system.org/pub/gap/gap47/tar.gz/packages/atlasrep1r5p0.tar.gz
  - wget ftp://ftp.gap-system.org/pub/gap/gap47/tar.gz/packages/ctbllib-1r2p2.tar.gz
  - wget ftp://ftp.gap-system.org/pub/gap/gap47/tar.gz/packages/grpconst-2.3.tar.gz
  - wget ftp://ftp.gap-system.org/pub/gap/gap47/tar.gz/packages/irredsol-1r2n4.tar.gz
  - wget ftp://ftp.gap-system.org/pub/gap/gap47/tar.gz/packages/tomlib1r2p4.tar.gz 
  - tar xvzf autpgrp-1.5.tar.gz
  - tar xvzf atlasrep1r5p0.tar.gz
  - tar xvzf ctbllib-1r2p2.tar.gz
  - tar xvzf grpconst-2.3.tar.gz
  - tar xvzf irredsol-1r2n4.tar.gz
  - tar xvzf tomlib1r2p4.tar.gz
  - cd ..
  - echo "Read(\"tst/${TEST_SUITE}.g\"); quit;" | sh bin/gap.sh -S | tee testlog.txt | grep --colour=always -E "########> Diff|$"
  - cat testlog.txt | grep "total"
  - ( ! grep "########> Diff" testlog.txt )
