#!/bin/sh
#########################################################################
##
#W  make_doc     make ANUSQ Share Package documentation  Alexander Hulpke
##
#H  $Id: make_doc,v 1.2 2002/06/12 19:15:18 gap Exp $
##
##  This shell script uses TeX, BibTeX and MakeIndex to  build  the  .dvi
##  PostScript (commented  out) and HTML (provided  you  have   tth   and
##  etc/convert.pl) documentation for the ACE Share Package.
##

echo "TeXing documentation"
# TeX the manual and build its bibliography
tex manual;bibtex manual
# TeX the manual again to incorporate the ToC ... and build the index
tex manual; ../../../doc/manualindex manual
# Finally TeX the manual again to get cross-references right
tex manual

# Generate pdf version
pdftex manual
pdftex manual

# The HTML version of the manual
mkdir -p ../htm
echo "Creating HTML documentation"
../../../etc/convert.pl -t -c -n ANUSQ . ../htm

#########################################################################
##
#E
