#!/bin/sh
#############################################################################
##
#W  processxpl         GAP 4 package '<pkgnam>'                 Thomas Breuer
##
#H  @(#)$Id: processxpl,v 1.1 2004/01/20 10:19:19 gap Exp $
##
#Y  Copyright (C)  2004,  Lehrstuhl D fuer Mathematik,  RWTH Aachen,  Germany
##
##  This script takes the file 'pkg/<pkgnam>/xpl/<name>.xpl'
##  and creates the dependent files (such as 'pkg/<pkgnam>/tst/<name>.tst'
##  and 'pkg/<pkgnam>/doc/<name>.tex') as described in the header of the
##  source file.
##
##  It must be called from the directory 'pkg/<pkgnam>',
##  in the form `etc/processxpl <name>'.
##
##  (This script is used in the packages `atlasrep', `ctbllib', `genus',
##  `gpisotyp'.)
##

grep '^%X  ' xpl/$1.xpl | sed -e 's/^%X  //' | sh

