#!/bin/sh
#########################################################################
##
#W  make_doc        make AutPGrp Package documentation        Greg Gamble
##
#H  $Id: make_doc,v 1.2 2003/10/01 11:39:27 gap Exp $
##
##  This shell script uses TeX, BibTeX and MakeIndex to  build  the .dvi,
##  PostScript (commented out), PDF, and  HTML  (provided  you  have  tth
##  and etc/convert.pl) documentation for the AutPGrp Package.
##

echo "TeXing documentation"
# TeX the manual
tex manual
# when there's a bibliography uncomment next line
#bibtex manual
# TeX the manual again to incorporate the ToC ... and build the index
tex manual; ../../../doc/manualindex manual
# Finally TeX the manual again to get cross-references right
tex manual
# Create the PostScript version (uncomment next line, if needed)
#dvips -D300 manual -o
# Create the PDF version (uncomment next line, if needed)
pdftex manual; pdftex manual

# The HTML version of the manual
mkdir -p ../htm
echo "Creating HTML documentation"
../../../etc/convert.pl -c -n AutPGrp . ../htm

#########################################################################
##
#E
