#!/bin/bash

# the version number needs to be updated!!!
VERSION=2r0p2;
XMLVERSION=2.0.2;

#define WORKDIR

# define variables

FILES="init.g read.g PackageInfo.g README";
NILPFILES="gap/nilpotent/nilpotent.gd gap/nilpotent/nilpotent.gi gap/nilpotent/nilpotent_data62.gi gap/nilpotent/nilpotent_data72.gi gap/nilpotent/nilpotent_data73.gi gap/nilpotent/nilpotent_data75.gi gap/nilpotent/nilpotent_data82.gi gap/nilpotent/nilpotent_data92.gi";
SLACFILES="gap/slac/slac.gd gap/slac/slac.gi";
NOSOFILES="gap/nonsolv/nonsolv.gd gap/nonsolv/nonsolv.gi gap/nonsolv/dim6char3iter.gi gap/nonsolv/nonsolvcoll.gi";
OTHEFILES="gap/doc.gi gap/liealgdb.gd gap/liealgdb.gi";
XMLFILES="doc/appnonsolv.xml doc/appsimple.xml doc/appsolv.xml doc/families.xml doc/manual.xml";
BIBFILES=doc/manual.bib;
DOCFILES="doc/manual.ps doc/manual.pdf doc/manual.pnr doc/manual.tex";
SIXFILES=doc/manual.six;
HTMFILES="doc/chap0.html doc/chap1.html doc/chap2.html doc/chap3.html doc/chapBib.html";
TXTFILES="doc/chap0.txt doc/chap1.txt doc/chap2.txt doc/chap3.txt doc/chapBib.txt";


#check if the version numbers are OK

OK=true

if grep Declare init.g | grep $XMLVERSION; then 
	echo init.g: version OK; 
else 
	echo init.g: version not OK -- exiting!; 
	exit 1; 
fi;

if grep Version PackageInfo.g | grep $XMLVERSION; then 
	echo PackageInfo.g: main version OK; 
else 
	echo PackageInfo.g: main version not OK -- exiting!; 
	exit 1; 
fi


if grep ArchiveURL PackageInfo.g | grep $VERSION; then 
	echo PackageInfo.g: archive version OK; 
else 
	echo PackageInfo.g: archive version not OK -- exiting!; 
	exit 1; 
fi

if grep "Archive " PackageInfo.g | grep $VERSION; then 
	echo PackageInfo.g: doc archive version OK; 
else 
	echo PackageInfo.g: doc archive version not OK -- exiting!; 
	exit 1; 
fi

if grep Version doc/manual.xml | grep $XMLVERSION; then 
	echo manual.xml: version OK; 
else 
	echo manual.xml: version not OK -- exiting!; 
	exit 1; 
fi

# create directories


mkdir liealgdb;
mkdir liealgdb/gap;
mkdir liealgdb/gap/slac;
mkdir liealgdb/gap/nonsolv;
mkdir liealgdb/gap/nilpotent;
mkdir liealgdb/doc

cp $FILES liealgdb;
cp $NILPFILES liealgdb/gap/nilpotent;
cp $SLACFILES liealgdb/gap/slac;
cp $NOSOFILES liealgdb/gap/nonsolv;
cp $OTHEFILES liealgdb/gap;
cp $XMLFILES liealgdb/doc;
cp $BIBFILES liealgdb/doc;
cp $DOCFILES liealgdb/doc;
cp $SIXFILES liealgdb/doc;
cp $HTMFILES liealgdb/doc;
cp $TXTFILES liealgdb/doc;


# copy

tar czf liealgdb$VERSION.tar.gz liealgdb
tar czf liealgdbdoc$VERSION.tar.gz liealgdb/doc

rm -r liealgdb



