#@local f, loc
gap> START_TEST("LocationFunc.tst");

#
gap> LocationFunc(fail);
Error, <func> must be a function

# regular GAP function
gap> f:=x->x;;
gap> LocationFunc(f);
"stream:1"

# Library function
gap> PositionSublist(LocationFunc(Where),"/lib/error.g:") <> fail;
true

# GAP function which was compiled to C code by gac
# this yields something like "GAPROOT/lib/oper1.g:147"
# but we don't want to depend on the changing line numbers,
# so we invest some extra work to test the format without
# relying on the specific content
gap> loc:=SplitString(LocationFunc(INSTALL_METHOD_FLAGS), ":");;
gap> Length(loc);
2
gap> loc[1] = "GAPROOT/lib/oper1.g";
true
gap> ForAll(loc[2], IsDigitChar);
true

# proper kernel function; this yields something like "src/listfunc.c:218".
# The line numbers reported for kernel functions are verified thoroughly in
# tst/testinstall/kernel/startline.tst
gap> loc:=SplitString(LocationFunc(APPEND_LIST_INTR), ":");;
gap> Length(loc);
2
gap> loc[1] = "src/listfunc.c";
true
gap> ForAll(loc[2], IsDigitChar);
true
gap> StartlineFunc(APPEND_LIST_INTR) = Int(loc[2]);
true

# kernel function generated by a C macro: its definition cannot be located in
# the source, so we fall back to naming the C function implementing it
gap> StartlineFunc(SIN_MACFLOAT);
fail
gap> LocationFunc(SIN_MACFLOAT);
"src/macfloat.c:FuncSIN_MACFLOAT"

# String is an attribute, so no information is stored
gap> LocationFunc( String );
fail

# functions created from a syntax tree have no location
gap> LocationFunc(SYNTAX_TREE_CODE(SYNTAX_TREE(x->x)));
fail

#
gap> STOP_TEST("LocationFunc.tst");
