#!/bin/sh
##########################################################################
##
##  cifix                                                    Werner Nickel
##
##  Commit a bug fix also to GAP 4 R 1 branch.
##
if [ X$1 = X-v ]; then
    verbose=1
    shift
else
    verbose=
fi

if [ $# -eq 0 ]; then
    echo "usage: cibugfix [-v] <file> ..."
    exit 1
fi

##
##  Loop through the file list
##
while [ $# -gt 0 ]; do

file=$1
ext=`echo $file | awk -F. '{print $2}'`

##
##  Get the revision number
##  In test files, the version number is the fourth thing, usually it is the 
##  third.
##
version=`cvs status $file | grep 'Working revision' | awk '{print $3}'`

##
##  Geth the version numbers.  We assume that the version number has
##  the form  m.n
##
major=`echo $version | awk -F. '{print $1}'`
minor=`echo $version | awk -F. '{print $2}'`

if [ $verbose ]; then
    echo File: $file
    echo Version: $major.$minor
fi

oldminor=$(($minor-1))

##
##  Checkout the branch 4R1  version
##
cvs update -r GAP4R1 $file

##
##  add in the differences between the current verion and the previous
##  version.
##
cvs update -j $major.$oldminor -j $major.$minor $file

##
##  check if there was a conflict
##
grep '<<<<<<<' $file > /dev/null

if [ $? -eq 0 ]; then

    ## Remove the merge conflict.
    awk -f ../etc/cifix.awk < $file > $file.awkout
    if [ $? -eq 7 ]; then

        rm $file.awkout

        echo ""
        echo "    Merge conflict -- cannot be resolved automatically."
        echo "    Edit $file and remove all conflicts, then run the"
        echo "    statements"
        echo "                   cvs commit $file"
        echo "                   cvs update -A $file"
        echo ""

    else

        echo ""
        echo "    Merge conflict automatically resolved"
        echo ""
        mv $file.awkout $file

        ##  Commit the fixed  4R1 version.
        cvs commit $file

        ##  Revert to the main branch
        cvs update -A $file
   
    fi

else 

    ##  Commit the fixed  4R1 version.
    cvs commit $file

    ##  Revert to the main branch
    cvs update -A $file
   
fi

shift

done
