#!/bin/tcsh
#
# merge a zoo file into another one. quick-n-dirty solution.
# (to be used to prepare a joint archive of zoo files for the release)
# ahulpke, 5-jul-99
# usage: zoomerge mergetoarchive otherarchive

# extract 
zoo lc $2 >infile
# build a wrapping file from the archive
# assume: header does not start with blank
# summary line starts with blank
awk 'BEGIN{com=0;}\
/^[ 0123456789]/{if (substr ($0,2,1) == "|" ) { \
  print "echo \"" substr($0,3) "\" > comment";\
  print "echo \"/END\" >>comment";\
  com=1;} \
else {if (com != 0) { print "zoo ahc blubber.zoo \"" name "\" < comment";} \
else {print "zoo ah blubber.zoo \"" name "\"";} \
print "rm -f \"" name "\""; \
name=substr($0,48);com=0; \
while ((length(name)>0)&&(substr(name,1,1)==" ") ) { \
  name=substr(name,2); \
} \
if (name !="") {print "unzoo -x -o '$2' \"" name "\"";} \
}}' infile >maches
chmod 755 maches
mv $1 blubber.zoo
sh maches
rm -f infile maches comment
mv blubber.zoo $1

