#!/bin/sh
#############################################################################
##
#W  checkout							 Frank Celler
##
##  this shell script checks out the next version
##
if [ -z "$BINDIR" ];  then
    echo "PANIC: you must set 'BINDIR'"
    exit 1
fi
if ${BINDIR}/checkvar;  then echo;  else
    exit 1
fi


# create an beta directory
cd ${DISTROOT}
rm -rf ${DISTNAME}


# checkout the files
echo "$0: exporting out version $FULLVERSION of $DATE"
#cvs -Q export -r ${CVSBRANCH} -d $DISTNAME 4.0
#cvs -Q export -d $DISTNAME 4.0
cvs -Q export -D "now" -d $DISTNAME 4.0
if [ \! -d ${DISTNAME} ];  then
    echo "PANIC: cvs did not create a distribution directory"
    exit 1
fi


# and add a tag
echo "tag! (currently disabled)!"
#echo "$0: tagging version $FULLVERSION of $DATE"
#cvs tag -F -D "$DATE" "GAP4R$VERSION"


# set the version
chmod 644 $DISTNAME/lib/system.g
#rm $DISTNAME/lib/version.g
#echo "VERSION := \"4.$FULLVERSION\";" > ${DISTNAME}/lib/version.g
#echo "DATE := \"$DATE\";" >> ${DISTNAME}/lib/version.g

sed "1,90s/4.dev/4.$FULLVERSION/g" ${DISTNAME}/lib/system.g > ${DISTNAME}/lib/vers2
sed "1,90s/today/$DATE/g" ${DISTNAME}/lib/vers2 > ${DISTNAME}/lib/system.g
rm -f ${DISTNAME}/lib/vers2

# that's it
exit 0
