#!/bin/sh
#############################################################################
##
#W  checkvar							 Frank Celler
##
##  this shell script checks the variables
##
if [ -z "$CVSROOT" ];  then
    echo "PANIC: you must set 'CVSROOT'"
    exit 1
fi

if [ -z "$DISTROOT" ];  then
    echo "PANIC: you must set 'DISTROOT'"
    exit 1
fi

if [ -z "$DISTNAME" ];  then
    echo "PANIC: you must set 'DISTNAME'"
    exit 1
fi

if [ -z "$VERSION" ];  then
    echo "PANIC: you must set 'VERSION'"
    exit 1
fi

if [ -z "$DATE" ];  then
    echo "PANIC: you must set 'DATE'"
    exit 1
fi

if [ -z "$LINUXPATH" ];  then
    echo "PANIC: you must set 'LINUXPATH'"
    exit 1
fi

if [ -z "$GAPEXEC" ];  then
    echo "PANIC: you must set 'GAPEXEC'"
    exit 1
fi

if [ -z "$TARDIR" ];  then
    echo "PANIC: you must set 'TARDIR'"
    exit 1
fi

exit 0
