#!/bin/sh
#############################################################################
##
#W  compile							 Frank Celler
##                                                           Alexander Hulpke
##
##  this shell script compiles the next version
##
if [ -z "$BINDIR" ];  then
    echo "PANIC: you must set 'BINDIR'"
    exit 1
fi
if ${BINDIR}/checkvar;  then echo;  else
    exit 1
fi


# go into the source directoy and compile
cd ${DISTROOT}/${DISTNAME}
# clean up
rm config.*
rm -rf bin/*gcc*

echo $0: making in the configure directory
cd cnf
make
make Makegap.in
cd ..

echo "$0: compiling version $FULLVERSION of $DATE"
./configure
make


# check that a executable has been created
if [ \! -x ${GAPEXEC} ];  then
    echo "PANIC: no executable '${GAPEXEC}' has been created"
    exit 1
fi

echo "============================================================="
echo "Creating completion files"
echo "CreateCompletionFiles();quit;" | ${GAPEXEC} -l ${DISTROOT}/${DISTNAME} -N -A -r

exit 0
