#!/bin/sh
#############################################################################
##
#W  doit							 Frank Celler
##
##  this shell script set the environment and then  calls to various programs
##  to extract the current  version, compile it, run  the test file, and  zoo
##  everything up
##
. `dirname $0`/setvar $1


# checkout the new version
echo "======================================================================"
echo
if ${BINDIR}/checkout;  then echo;  else
    echo "PANIC: cannot checkout the next version"
    exit 1
fi


# compile the new version
echo
echo "======================================================================"
echo
if ${BINDIR}/compile;  then echo;  else
    echo "PANIC: cannot compile the next version"
    exit 1
fi

# winooze compile
echo
echo "======================================================================"
echo
if ${BINDIR}/windowscompile;  then echo;  else
    echo "PANIC: cannot create winooze version"
    exit 1
fi


# TeX documentation
echo
echo "======================================================================"
echo
if ${BINDIR}/texdoc;  then echo;  else
    echo "PANIC: cannot TeX the documentation"
    exit 1
fi


# run the test files the new version
echo
echo "======================================================================"
echo
if ${BINDIR}/readtest;  then echo;  else
    echo "PANIC: cannot run the test files"
    exit 1
fi


# zoo the new version
echo
echo "======================================================================"
echo
if ${BINDIR}/zooit;  then echo;  else
    echo "PANIC: cannot zoo the next version"
    exit 1
fi

echo
echo "======================================================================"
echo

exit 0

