#!/bin/sh
#############################################################################
##
#W  setvar							 Frank Celler
##
##  this shell script sets the variables
##

# where does the CVS directory live
#CVSROOT="/gap/CVS"
CVSROOT=":pserver:gap@cvs-gap.dcs.st-and.ac.uk:/gap/CVS"

#-----------------------------------------------------------------------------
# everything below should be system independent.

# binary directory
BINDIR=`pwd`

PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/home/fac/a/hulpke/bin


# where to put the version
DISTROOT=/scratch/gap4dist
if [ \! -d ${DISTROOT} ];  then
    mkdir $DISTROOT
fi


# what is *this moment*
DATE=`date +"%d-%b-%Y"`


VERSION="${1}"
FULLVERSION="${1}.${2}"

echo "Creating Version $FULLVERSION"

# where does the directory live
RBVERSION="4r$VERSION"
DISTNAME="gap$RBVERSION"
LINUXPATH=bin/i686-pc-linux-gnu-gcc
GAPEXEC=${DISTROOT}/${DISTNAME}/${LINUXPATH}/gap

# the tar directory
TARDIR=/scratch
umask 022

PKGLOC=http://www.math.rwth-aachen.de:8001/~Frank.Luebeck/tmp/Packages/
PKGARCH=mergepkg-2003_10_02-15_26_UTC.tar.gz


# export these variables
export CVSROOT CVSBRANCH DISTROOT VERSION FULLVERSION BINDIR DATE LINUXPATH GAPEXEC TARDIR DISTNAME RBVERSION PKGLOC PKGARCH


