#!/bin/sh
#############################################################################
##
#W  texdoc						     Alexander Hulpke
##
##  this shell script TeXs the next version
##
if [ -z "$BINDIR" ];  then
    echo "PANIC: you must set 'BINDIR'"
    exit 1
fi
if ${BINDIR}/checkvar;  then echo;  else
    exit 1
fi

cd ${DISTROOT}/${DISTNAME}/doc

# NB: copying psfonts.map will make dvips use the type1 outline fonts. This
# assumes that the pfb files for these fonts are locally installed
# (otherwise the ps files are corrupt).
# The `cmps' fonts are installed on muir and shades.
cp ../mkdistrib/psfonts.map tut
cp ../mkdistrib/psfonts.map ref
cp ../mkdistrib/psfonts.map prg
cp ../mkdistrib/psfonts.map ext
cp ../mkdistrib/psfonts.map new

# build the documentation
./make_doc

# fetch the `INSTALL' files from the manual
cd htm/ref
rm -rf ../../../../INSTALL*
lynx -dump -nolist -underscore `fgrep -l "Porting GAP" C*.htm`| awk -f ${BINDIR}/instfiles.awk

cat ${BINDIR}/INSTALL.hdr ../../../../INSTALL > tempfile
mv tempfile ../../../../INSTALL
cat ${BINDIR}/INSTALL.WIN.hdr ../../../../INSTALL.WIN > tempfile
mv tempfile ../../../../INSTALL.WIN
cat ${BINDIR}/INSTALL-MAC.hdr ../../../../INSTALL-MAC.TXT > tempfile
mv tempfile ../../../../INSTALL-MAC.TXT
rm tempfile

# the small HTML version
echo "small HTML documentation"
cd ../..
mkdir htm_small
cd htm_small
cp ../htm/Makefile .
cp ../htm/onehtmlindex .
cp ../htm/allhtmlindex .
mkdir ref tut ext prg new
make webdoc

exit 0
