#!/bin/sh
#############################################################################
##
#W  texdoc						     Alexander Hulpke
##
##  this shell script TeXs the next version
##
if [ -z "$BINDIR" ];  then
    echo "PANIC: you must set 'BINDIR'"
    exit 1
fi
if ${BINDIR}/checkvar;  then echo;  else
    exit 1
fi

cd ${DISTROOT}/${DISTNAME}/doc

# NB: copying psfonts.map will make dvips use the type1 outline fonts. This
# assumes that the pfb files for these fonts are locally installed
# (otherwise the ps files are corrupt).
# The `cmps' fonts are installed on muir and shades.
cp ../mkdistrib/psfonts.map tut
cp ../mkdistrib/psfonts.map ref
cp ../mkdistrib/psfonts.map prg
cp ../mkdistrib/psfonts.map ext
cp ../mkdistrib/psfonts.map new

# build the documentation
./make_doc

# this is the mozilla version. Build IE version
cp -r htm htmmoz
(cd htm;make clean;make ieversion)
mv htm htmie
mv htmmoz htm

# fetch the `INSTALL' files from the manual
grep -v "^%" ref/README.tex > ../../README

exit 0
