#!/bin/sh
#############################################################################
##
#W  zooit							 Frank Celler
#W       						     Alexander Hulpke
##
##  this shell script zoos up the next version
##
if [ -z "$BINDIR" ];  then
    echo "PANIC: you must set 'BINDIR'"
    exit 1
fi
if ${BINDIR}/checkvar;  then echo;  else
    exit 1
fi

chmod a+x ${BINDIR}/saytext
chmod a+x ${BINDIR}/saybin


# clean the old files
cd ${DISTROOT}
[ -d OLD ] || mkdir OLD
rm -rf OLD/*
mv [a-z]*.zoo [a-z]*.tar [a-z]*.zip [a-z]*.tar.gz OLD

# remove things that should not go in the distribution

echo "Cleaning up before wrapping"
(cd $DISTROOT/$DISTNAME;

rm -rf doc/build doc/abattoir doc/Makefile alpha beta dev dev \
  config.*

find . -name .cvsignore -exec rm {} \;
)


# go into the source directory and create the zoo files
echo "$0: zooing version $FULLVERSION of $DATE"

#echo "README file"
#cp ${DISTNAME}/etc/README .

. ${BINDIR}/zoofuncs

(cd $DISTROOT;

echo "Basic stuff"
for j in lib grp tst; do
    addtext gap$RBVERSION ${DISTNAME}/${j}/*
done
addtext gap$RBVERSION ${DISTNAME}/etc/*.vim ${DISTNAME}/etc/emacs/* ${DISTNAME}/etc/xrmtcmd.c
addtext gap$RBVERSION ${DISTNAME}/etc/GPL

echo "Documentation -- TeX files"

for j in ref tut ext prg new; do
    addtext gap$RBVERSION ${DISTNAME}/doc/${j}/*.tex

done

for i in gapmacro.tex manual.bib manualindex; do
    addtext gap$RBVERSION ${DISTNAME}/doc/$i
done

for j in six mst; do
    addtext gap$RBVERSION ${DISTNAME}/doc/{ref,tut,ext,prg,new}/manual.$j
done

echo "Source files"

cp ${BINDIR}/FILES .

addtext gap$RBVERSION README
addbin gap$RBVERSION ${DISTNAME}/gap.shi

for j in src cnf; do
    addbin gap$RBVERSION ${DISTNAME}/${j}/*
done

for i in  ${DISTNAME}/{Makefile.in,sysinfo.in,configure}; do
    addbin gap$RBVERSION $i
done


echo "TeXed Documentation"
addbin gap$RBVERSION ${DISTNAME}/doc/*/manual.dvi
addbin gap$RBVERSION ${DISTNAME}/doc/*/manual.pdf
addbin gap$RBVERSION  ${DISTNAME}/doc/fullindex.pdf

echo "HTML Documentation"

for j in ref tut ext prg new; do
  addtext gap$RBVERSION ${DISTNAME}/doc/htm/${j}/*
  addtext htmie$RBVERSION ${DISTNAME}/doc/htmie/${j}/*
done

for i in ${DISTNAME}/doc/htm/*.htm; do
    addtext gap$RBVERSION $i
done

for i in ${DISTNAME}/doc/htmie/*.htm; do
    addtext htmie$RBVERSION $i
done

echo "Trans"
addtext gap$RBVERSION ${DISTNAME}/trans/*

echo "Prim"

addtext gap$RBVERSION ${DISTNAME}/prim/*.* ${DISTNAME}/prim/grps/*

echo "Winbin"
cp ${DISTNAME}/bin/i686-pc-cygwin-gcc/gap.exe ${DISTNAME}/bin/gapw95.exe
addbin gap$RBVERSION ${DISTNAME}/bin/gapw95.exe
addbin gap$RBVERSION ${DISTNAME}/bin/rxvt.exe
addbin gap$RBVERSION ${DISTNAME}/bin/regtool.exe
addbin gap$RBVERSION ${DISTNAME}/bin/cygwin1.dll
addbin gap$RBVERSION ${DISTNAME}/bin/libW11.dll
addbin gap$RBVERSION ${DISTNAME}/bin/gap.pif
addbin gap$RBVERSION ${DISTNAME}/bin/gapicon.bmp
addtext gap$RBVERSION ${DISTNAME}/bin/gaprxvt.bat
addtext gap$RBVERSION ${DISTNAME}/bin/gap.bat
addtext gap$RBVERSION ${DISTNAME}/bin/usemem.bat

rm ${DISTNAME}/bin/{gapw95.exe,cygwin1.dll}

##  echo "Mac src"
##  find ${DISTNAME}/{macsrc,macgac} -print | zoo ahI macsrc$RBVERSION.zoo > /dev/null

# small is at the end since its many files. 
echo "Small"

addtext gap$RBVERSION ${DISTNAME}/small/*.*

for k in id2 id3 id4 id5 small2 small3 small4 small5 small6 small7 small8; do
    echo "     " $k
    addtext gap$RBVERSION ${DISTNAME}/small/${k}/*
done

#
# Have to do id6 separately because it's too many files
#

echo "     " id6
addtext gap$RBVERSION ${DISTNAME}/small/id6/id1152.*
addtext gap$RBVERSION ${DISTNAME}/small/id6/id1920.*
addtext gap$RBVERSION ${DISTNAME}/small/id6/*.g

echo "Tom -- only for 4.4"

for j in pkg/tomlib/PackageInfo.g pkg/tomlib/init.g pkg/tomlib/read.g; do
  addtext gap$RBVERSION ${DISTNAME}/${j}
done
addtext gap$RBVERSION ${DISTNAME}/pkg/tomlib/gap/*

for j in tmlin2mx tmlinoam tmlin2a tmprimar tmaltc tmx3l34 tmsymc tmutwam tmutwa tmutwmx tmlin2 tmunitc tmutw tmmathmx.tom tmunitcm tmjankmx tmtw tmmath tmsym1mx tmlinoa tmesym tmsympam tmsympa tmjank tmtwmx tmalt1 tmhsmclm tmunit tmunitam tmunitmx tmsympmx tmhsmcl tmlinomx tmalt1mx tmunita tmlino tmsymp tmsym1 tmealt tmhe tms11 tma12 tmco3 ; do
  addtext gap$RBVERSION ${DISTNAME}/pkg/tomlib/data/${j}.tom
done;

echo "xtom"
for j in tma12m9 tmco3mx tms10m1 tmo82mx.tom tm2s62mx tms62mx6 tms62mx3 tma12m4 tm4l34mx tm2s62m6 tm2s62 tms10m2 tm2s62m3 tml52 tmu43v4 tms11m3 tma12mx tmm24 tmm24m7 tmhemx tm4l34 tmu43v4m tmm24m5 tms11m4 tms11m6 tma12m5 tms11m5 tm4l34s3 tm3d42 tm3d42m1 tmg24 tmo8m2 tmo8m2m1 tmo8p2 tmo8p2m4; do
  addtext xtom$RBVERSION ${DISTNAME}/pkg/tomlib/data/${j}.tom
done

echo "tools"

addtext tools${RBVERSION} ${DISTNAME}/doc/{allmanualsindex,gapmacro.tex,make_doc,mrabbrev.bib}
addtext tools${RBVERSION} ${DISTNAME}/doc/{fullindex.tex,fullindex.mst}
addtext tools${RBVERSION} ${DISTNAME}/doc/{manualindex,htm/Makefile,htm/allhtmlindex,htm/onehtmlindex}
addtext tools${RBVERSION} ${DISTNAME}/etc/{buildman.pe,convert.pl,packpack,unzoo.c,README.tools}

)

exit 0
