#############################################################################
##
##  normpro.gd                      CRISP                    Burkhard Höfling
##
##  @(#)$Id: normpro.gd,v 1.3 2011/05/15 19:17:56 gap Exp $
##
##  Copyright (C) 2000 Burkhard Höfling
##
Revision.normpro_gd :=
    "@(#)$Id: normpro.gd,v 1.3 2011/05/15 19:17:56 gap Exp $";


#############################################################################
##
#O  NormalizerOfPronormalSubgroup (<grp>, <sub>)
##
##  returns the normalizer of <sub> in <grp>. <sub> must be a pronormal
##  subgroup of <grp>, i.e., for every g in <grp>, <sgr> and <sgr>^g > 
##  are conjugate in their join.
##
DeclareOperation ("NormalizerOfPronormalSubgroup", [IsGroup, IsGroup]);


#############################################################################
##
#O  PcgsNormalizerOfPronormalSubgroup (<pcgs>, <ppcgs>
##
##  returns the normalizer of the group generated by <ppcgs> in <pcgs>. 
##  The former must must be pronormal in the latter (in particular,
##  it must be a subgroup (which we don't check).
##
DeclareOperation ("PcgsNormalizerOfPronormalSubgroup", [IsPcgs, IsPcgs]);


#############################################################################
##
#V  InfoNormalizer
##
DeclareInfoClass ("InfoNormalizer");


############################################################################
##
#E
##
