#!/bin/sh
# (C) Frank Lübeck

mypath=`dirname  $0`/

source ${mypath}setvarpkg

if [ "$#" != "1" ]; then
  echo "Usage: addPackages <urlsfile>"
  exit 1
fi;

echo "Checking the list of PackageInfo.g URLs"

$GAP -r -b -q  ${mypath}PackageInfoTools.g  << EOI
ANSI_COLORS := false;;
Unbind(PrintPromptHook);
AddPackages("${PkgCacheDir}", "${PkgReposDir}", "$1"); 
quit;
EOI
