#!/bin/sh -ex
# $Id$    (C) Frank Lübeck

mypath=`dirname  $0`/

source ${mypath}setvarpkg

cd ${PkgWebFtpDir}/ftpdir

echo "Dry run:"
rsync -av -c -n tar.gz tar.bz2 win.zip zip ${FtpServer}
read -n 1 -p "Shall I copy? (y/n)> " ANSWER
echo

if [ $ANSWER = "y" ]; then
  echo "Ok, I'll copy ..."
  rsync -av -c tar.gz tar.bz2 win.zip zip ${FtpServer}
else
  echo "Don't copy, bye."
fi

