#!/bin/sh
# (C) Frank Lübeck


mypath=`dirname  $0`/

source ${mypath}setvarpkg

echo "This script uses one argument which must be the name of the archive"
echo "with the timestamp without extension, e.g. gap4r5p4_2012_06_04-23_02"
echo "For each package, it will tag its stable version with the given tag."
echo "Therefore, you must ensure that it matches current stable versions."
echo " "
echo "Going to tag stable versions of all packages with the following tag:"
echo " "
echo "        "$1
echo " "
read -n 1 -p "Are you sure to continue? (y/n)> " ANSWER
echo

if [ $ANSWER = "y" ]; then

$GAP -r -b -q  ${mypath}PackageInfoTools.g  << EOI
ANSI_COLORS := false;;
Unbind(PrintPromptHook);
Print("\n");

markAllStableWithTimestamp(
  "${PkgReposDir}",
  "$1" );
quit;
EOI

else
  echo "I will not do it, bye."
fi