#!/bin/sh
# (C) Frank Lübeck

# path to the directory which will contain directories needed by the 
# packages update mechanism (pkgcache, webftp, mergedarchives, tmp, WWW2).
# no trailing "/" is needed since all subdirectories below start with "/".
# "/mnt/raid/hudson-slave/..." is the path used by Jenkins continuous build 
# system.

export PREFIX="/mnt/raid/hudson-slave/workspace/GAP-pkg-update/pkgadmin"

# how to call GAP, e.g. "/gap/bin/gapL", "gap" or "gap45"
export GAP="gap"

# path to directory for caching PackageInfo.g, archive and unpacked
# package documentation
export PkgCacheDir=${PREFIX}"/pkgcache"

# path to directory for files for export to ftp/web site
export PkgWebFtpDir=${PREFIX}"/webftp"

# path to directory for collecting merged archives (will contain the current 
# packages-... files and subdirectory 'old' holding the older versions
export PkgMergedArchiveDir=${PREFIX}"/mergedarchives"

# temporary directory for merging the package archives
export PkgMergeTmpDir=${PREFIX}"/tmp"

# directory with a CVS checkout of WWW2 (only subdir 'Packages' is needed)
export WWW2Dir=${PREFIX}"/WWW2"

# destination of the ftp server directory (can be remote), the one
# containing the directories 'tar.gz', 'tar.bz2' and 'win.zip'
export FtpServer="/ftp/pub/gap/gap45"

# destination of the directory containing package release repositories 
# (that is, repositories to store released versions of the package to
# use in the GAP package update mechanism; NOT to store development 
# versions of packages
export PkgReposDir="/mnt/raid/gap-packages-archive"
