#!/bin/sh -ex
# (C) Frank Lübeck

mypath=`dirname  $0`/

source ${mypath}setvarpkg

if [ "$#" != "1" ]; then
  echo "Usage: storeLegacyPackage <path-to/archive>"
  exit 1
fi;

$GAP -r -b -q  ${mypath}PackageInfoTools.g  << EOI
ANSI_COLORS := false;;
Unbind(PrintPromptHook);
StoreLegacyPackageArchive("$1","${PkgReposDir}"); 
quit;
EOI

