#!/bin/sh -ex
# (C) Frank Lübeck


mypath=`dirname  $0`/

source ${mypath}setvarpkg

$GAP -r -b -q  ${mypath}PackageInfoTools.g  << EOI
ANSI_COLORS := false;;
Unbind(PrintPromptHook);
Print("\n");


newdocs := UpdatePackageDoc("${PkgReposDir}", "${PkgWebFtpDir}/Packages/pkg");;
if Length(newdocs) > 0 then
  Print("\nThe following manual books were retrieved:\n", newdocs, "\n");
else
  Print("\nAll online manual books are up to date!\n");
fi;

quit;
EOI

