#!/bin/sh
# $Id$    (C) Frank Lübeck


mypath=`dirname  $0`/

source ${mypath}setvarpkg

$GAP -r -b -q  ${mypath}PackageInfoTools.g  << EOI
ANSI_COLORS := false;;
Unbind(PrintPromptHook);
Print("\n");

ReadAllPackageInfos("${PkgCacheDir}");
WritePackageWebPageInfos("${PkgWebFtpDir}", 
                            "${PkgWebFtpDir}/Packages/pkgconf.py");

quit;
EOI

${mypath}currentPackageInfoURLs

