#!/bin/sh -ex
# (C) Frank Lübeck


mypath=`dirname  $0`/

source ${mypath}setvarpkg

$GAP -r -b -q  ${mypath}PackageInfoTools.g  << EOI
ANSI_COLORS := false;;
Unbind(PrintPromptHook);
Print("\n");

ReadAllPackageInfos("${PkgReposDir}");
WritePackageWebPageInfos("${PkgWebFtpDir}", 
                         "${PkgWebFtpDir}/Packages/pkgconf.py",
                         "${PkgWebFtpDir}/Packages/pkgstaticlist" 
);
quit;
EOI

