-----
minimal,
2,
gens(a,b),
rels(b^4,b^2=[[b,a],a],b=a^2*b^-1*a^2);
-----
2,
gens(a,b,c,d),
rels(b^4,b^2=[[b,a],a],d^16,a^16=c*d,b^8=d*c^4);
-----
minimal,
3,
gens(x,y),
rels([[[x,y],x],y],([[y,x],y])^3,(x*y*x)^3);
-----
minimal,
3,
gens(a,b),
rels((a^2*b)^3=[[b,a],a],[[[b,a],a],b]=(a*b^-1)^9);
-----
minimal,
5,
gens(a,b),
rels(a^25,[[[[[b,a],b],b],b],b],b^5,[[b,a],a]);
-----
minimal,
5,
gens(a,b),
rels(a^5,b^5,[[b,a],b]);
-----
minimal,
7,
gens(a,b),
rels(b^7,a^7=[[b,a],b],(a*b*[[b,a],b])^7,[[[[[[b,a],a],a],a],b],a]);
-----
minimal,
7,
gens(a,b),
rels(b^7=[[b,a],a],[[b,a],b]);
-----
minimal,
11,
gens(a,b),
rels(a^11,b^11=([[b,a],a])^2,[[[[[b,a],b],b],b],b]);
-----
minimal,
11,
gens(a,b,c),
rels(a^11,b^11,c^11,[[[[[b,a],a],a],b],a],[c,a],[c,b],[[b,a],b]);
