#############################################################################
##
#W  sml512.r               GAP library of groups           Hans Ulrich Besche
##                                               Bettina Eick, Eamonn O'Brien
##

SMALL_GROUP_LIB[ 512 ][ 18 ] := `[
"%%%%%//Yh0&,,8%&D8,,%E%%&%8,%%!]Vq5<!]uq(Y!Bth(Y!Buh(Y!Btq(Y!Buq(Y!^th(Y!^u\
h(Y!^tq(Y!^uq(Y!Awh(Y!Axh(Y!Awq(Y!Axq(Y!]wh(Y!]xh(Y!J<q.c",
"%%%%%/8Yh09,,8%&D8,,%E%%(%8,%%!U.KV<V!U.TV(Y!L7K8(Y!L7T8(Y!L7KV(Y!L7TV(Y!U7\
K8(Y!U7T8(Y!U7KV(Y!U7TV(Y!.L,8(Y!.L58(Y!.L,V(Y!.L5V(Y!7L,8(Y!7L58(X",
"%%%%%/%Yh00,,8%&D8,,%E%%%%8,%%!SWe-b!]tq(Y!]uq(Y!Bth(Y!Buh(Y!Btq(Y!Buq(Y!^t\
h(Y!^uh(Y!^tq(Y!^uq(Y!Awh(Y!Axh(Y!Awq(Y!Axq(Y!]wh(Y!]=h(}",
"%%%%%/%Yh00,,8%&D8,,%E%%(%8,%%!]Zd(}!]wg(Y!]xg(Y!Bwd(Y!Bxd(Y!Bwg(Y!Bxg(Y!^w\
d(Y!^xd(Y!^wg(Y!^xg(Y!Atm(Y!Aum(Y!Atp(Y!Aup(Y!]tm(Y!J9k-b",
"%%%%%/%Yh00,,8%&D8,,%E%%&%8,%%!]uh53!]tq(Y!]uq(Y!Bth(Y!Buh(Y!Btq(Y!Buq(Y!^t\
h(Y!^uh(Y!^tq(Y!^uq(Y!Awh(Y!Axh(Y!Awq(Y!Axq(Y!]wh(W",
"%%%%%/8Yh00,,8%&D8,,%E%%(%8,%%!46<b.c!7BYb(Y!7B=b(Y!7BZb(Y!.^<b(Y!.^Yb(Y!.^\
=b(Y!.^Zb(Y!7^<b(Y!7^Yb(Y!7^=b(Y!7^Zb(Y!LA8b(Y!LAVb(Y!LA9b(Y!LAWb(Y!U,8b({",
"%%%%%//Yh00,,8%&D8,,%E%%%%8,%%!]th<]!]uh(Y!]tq(Y!]uq(Y!Bth(Y!Buh(Y!Btq(Y!Bu\
q(Y!^th(Y!^uh(Y!^tq(Y!^uq(Y!Awh(Y!Axh(Y!Awq(Y!Axq(Y",
"%%%%%//Yh00,,8%&D8,,%E%%(%8,%%!]wd(Y!]xd(Y!]wg(Y!]xg(Y!Bwd(Y!Bxd(Y!Bwg(Y!Bx\
g(Y!^wd(Y!^xd(Y!^wg(Y!^xg(Y!Atm(Y!Aum(Y!Atp(Y!Aup(V",
"%%%%%//Yh00,,8%&D8,,%E%%&%8,%%!AWq5<!]th(Y!]uh(Y!]tq(Y!]uq(Y!Bth(Y!Buh(Y!Bt\
q(Y!Buq(Y!^th(Y!^uh(Y!^tq(Y!^uq(Y!Awh(Y!Axh(Y!Awq(Y!,=q.c",
"%%%%%/8Yh09,,8%(D8,,%E%b(%8,%%!LLR4<V!ULO1(Y!ULR1(Y!ULO4(Y!ULR4(Y!LUO1(Y!LU\
R1(Y!LUO4(Y!LUR4(Y!UUO1(Y!UUR1(Y!UUO4(Y!UUR4(Y!..(F(Y!..+F(Y!..(I(X",
"%%%%%/%Yh0&,,8%%D8,,%E%D%%8,%%!5Vn-b!Auq(Y!]th(Y!]uh(Y!]tq(Y!]uq(Y!Bth(Y!Bu\
h(Y!Btq(Y!Buq(Y!^th(Y!^uh(Y!^tq(Y!^uq(Y!Awh(Y!Axh(Y!A<q(}",
"%%%%%/%Yh0&,,8%%D8,,%E%D(%8,%%!AYg(}!Axg(Y!]wd(Y!]xd(Y!]wg(Y!]xg(Y!Bwd(Y!Bx\
d(Y!Bwg(Y!Bxg(Y!^wd(Y!^xd(Y!^wg(Y!^xg(Y!Atm(Y!Aum(Y!,8n-b",
"%%%%%/%Yh0&,,8%%D8,,%E%D&%8,%%!Atq53!Auq(Y!]th(Y!]uh(Y!]tq(Y!]uq(Y!Bth(Y!Bu\
h(Y!Btq(Y!Buq(Y!^th(Y!^uh(Y!^tq(Y!^uq(Y!Awh(Y!Axh(W",
"%%%%%/8Yh0&,,8%%D8,,%E%D(%8,%%!+6Yb.c!.B=b(Y!.BZb(Y!7B<b(Y!7BYb(Y!7B=b(Y!7B\
Zb(Y!.^<b(Y!.^Yb(Y!.^=b(Y!.^Zb(Y!7^<b(Y!7^Yb(Y!7^=b(Y!7^Zb(Y!LA8b(Y!L,Vb({",
"%%%%%//Yh0&,,8%%D8,,%E%D%%8,%%!Auh<]!Atq(Y!Auq(Y!]th(Y!]uh(Y!]tq(Y!]uq(Y!Bt\
h(Y!Buh(Y!Btq(Y!Buq(Y!^th(Y!^uh(Y!^tq(Y!^uq(Y!Awh(Y",
"%%%%%//Yh0&,,8%%D8,,%E%D(%8,%%!Axd(Y!Awg(Y!Axg(Y!]wd(Y!]xd(Y!]wg(Y!]xg(Y!Bw\
d(Y!Bxd(Y!Bwg(Y!Bxg(Y!^wd(Y!^xd(Y!^wg(Y!^xg(Y!Atm(V",
"%%%%%//Yh0&,,8%%D8,,%E%D&%8,%%!AVh5<!Auh(Y!Atq(Y!Auq(Y!]th(Y!]uh(Y!]tq(Y!]u\
q(Y!Bth(Y!Buh(Y!Btq(Y!Buq(Y!^th(Y!^uh(Y!^tq(Y!^uq(Y!,<h.c",
"%%%%%//Yh0&,,8%%D/,,%E%D&%8,%%!Av8<V!Ay8(Y!AvV(Y!AyV(Y!]v8(Y!]y8(Y!]vV(Y!]y\
V(Y!Bv8(Y!By8(Y!BvV(Y!ByV(Y!^v8(Y!^y8(Y!^vV(Y!^yV(X",
"%%%%%/8Yh09,,8%%D8,,%E%D(%8,%%!R4TM-b!.L,8(Y!.L58(Y!.L,V(Y!.L5V(Y!7L,8(Y!7L\
58(Y!7L,V(Y!7L5V(Y!.U,8(Y!.U58(Y!.U,V(Y!.U5V(Y!7U,8(Y!7U58(Y!7U,V(Y!7O5V(}",
"%%%%%/%Yh00,,8%%D8,,%E%D%%8,%%!^Wq(}!Awh(Y!Axh(Y!Awq(Y!Axq(Y!]wh(Y!]xh(Y!]w\
q(Y!]xq(Y!Bwh(Y!Bxh(Y!Bwq(Y!Bxq(Y!^wh(Y!^xh(Y!^wq(Y!K=k-b",
"%%%%%/%Yh00,,8%%D8,,%E%D(%8,%%!^xg53!Atm(Y!Aum(Y!Atp(Y!Aup(Y!]tm(Y!]um(Y!]t\
p(Y!]up(Y!Btm(Y!Bum(Y!Btp(Y!Bup(Y!^tm(Y!^um(Y!^tp(W",
"%%%%%/%Yh00,,8%%D8,,%E%D&%8,%%!TVq.c!^uq(Y!Awh(Y!Axh(Y!Awq(Y!Axq(Y!]wh(Y!]x\
h(Y!]wq(Y!]xq(Y!Bwh(Y!Bxh(Y!Bwq(Y!Bxq(Y!^wh(Y!^xh(Y!^<q({",
"%%%%%/8Yh00,,8%%D8,,%E%D(%8,%%!7^=b<]!7^Zb(Y!LA8b(Y!LAVb(Y!LA9b(Y!LAWb(Y!UA\
8b(Y!UAVb(Y!UA9b(Y!UAWb(Y!L]8b(Y!L]Vb(Y!L]9b(Y!L]Wb(Y!U]8b(Y!U]Vb(Y",
"%%%%%//Yh00,,8%%D8,,%E%D%%8,%%!^tq(Y!^uq(Y!Awh(Y!Axh(Y!Awq(Y!Axq(Y!]wh(Y!]x\
h(Y!]wq(Y!]xq(Y!Bwh(Y!Bxh(Y!Bwq(Y!Bxq(Y!^wh(Y!^xh(V",
"%%%%%//Yh00,,8%%D8,,%E%D(%8,%%!^Zd5<!^wg(Y!^xg(Y!Atm(Y!Aum(Y!Atp(Y!Aup(Y!]t\
m(Y!]um(Y!]tp(Y!]up(Y!Btm(Y!Bum(Y!Btp(Y!Bup(Y!^tm(Y!K9m.c",
"%%%%%//Yh00,,8%%D8,,%E%D&%8,%%!^uh<V!^tq(Y!^uq(Y!Awh(Y!Axh(Y!Awq(Y!Axq(Y!]w\
h(Y!]xh(Y!]wq(Y!]xq(Y!Bwh(Y!Bxh(Y!Bwq(Y!Bxq(Y!^wh(X",
"%%%%%/8Yh09,,8%(D8,,%E%D(%8,%%!RR1G-b!UU4J(Y!UU1S(Y!UU4S(Y!..F,(Y!..I,(Y!..\
F5(Y!..I5(Y!7.F,(Y!7.I,(Y!7.F5(Y!7.I5(Y!.7F,(Y!.7I,(Y!.7F5(Y!.7I5(Y!71F,(}",
"%%%%%/%Yh0&,,8%&D8,,%E%D%%8,%%!^Vh(}!^uh(Y!^tq(Y!^uq(Y!Awh(Y!Axh(Y!Awq(Y!Ax\
q(Y!]wh(Y!]xh(Y!]wq(Y!]xq(Y!Bwh(Y!Bxh(Y!Bwq(Y!Bxq(Y!K<b-b",
"%%%%%/%Yh0&,,8%&D8,,%E%D(%8,%%!^wd53!^xd(Y!^wg(Y!^xg(Y!Atm(Y!Aum(Y!Atp(Y!Au\
p(Y!]tm(Y!]um(Y!]tp(Y!]up(Y!Btm(Y!Bum(Y!Btp(Y!Bup(W",
"%%%%%/%Yh0&,,8%&D8,,%E%D&%8,%%!6Wq.c!^th(Y!^uh(Y!^tq(Y!^uq(Y!Awh(Y!Axh(Y!Aw\
q(Y!Axq(Y!]wh(Y!]xh(Y!]wq(Y!]xq(Y!Bwh(Y!Bxh(Y!Bwq(Y!B=q({",
"%%%%%/8Yh0&,,8%&D8,,%E%D(%8,%%!.^Zb<]!7^<b(Y!7^Yb(Y!7^=b(Y!7^Zb(Y!LA8b(Y!LA\
Vb(Y!LA9b(Y!LAWb(Y!UA8b(Y!UAVb(Y!UA9b(Y!UAWb(Y!L]8b(Y!L]Vb(Y!L]9b(Y",
"%%%%%//Yh0&,,8%&D8,,%E%D%%8,%%!Buq(Y!^th(Y!^uh(Y!^tq(Y!^uq(Y!Awh(Y!Axh(Y!Aw\
q(Y!Axq(Y!]wh(Y!]xh(Y!]wq(Y!]xq(Y!Bwh(Y!Bxh(Y!Bwq(V",
"%%%%%//Yh0&,,8%&D8,,%E%D(%8,%%!BYg5<!Bxg(Y!^wd(Y!^xd(Y!^wg(Y!^xg(Y!Atm(Y!Au\
m(Y!Atp(Y!Aup(Y!]tm(Y!]um(Y!]tp(Y!]up(Y!Btm(Y!Bum(Y!-8p.c",
"%%%%%//Yh0&,,8%&D8,,%E%D&%8,%%!Btq<V!Buq(Y!^th(Y!^uh(Y!^tq(Y!^uq(Y!Awh(Y!Ax\
h(Y!Awq(Y!Axq(Y!]wh(Y!]xh(Y!]wq(Y!]xq(Y!Bwh(Y!Bxh(X",
"%%%%%/8Yh09,,8%&D8,,%E%D(%8,%%!I4T/-b!L7KV(Y!L7TV(Y!U7K8(Y!U7T8(Y!U7KV(Y!U7\
TV(Y!.L,8(Y!.L58(Y!.L,V(Y!.L5V(Y!7L,8(Y!7L58(Y!7L,V(Y!7L5V(Y!.U,8(Y!.O58(}",
"%%%%%/%Yh00,,8%&D8,,%E%D%%8,%%!BWh(}!Btq(Y!Buq(Y!^th(Y!^uh(Y!^tq(Y!^uq(Y!Aw\
h(Y!Axh(Y!Awq(Y!Axq(Y!]wh(Y!]xh(Y!]wq(Y!]xq(Y!Bwh(Y!-=b-b",
"%%%%%/%Yh00,,8%&D8,,%E%D(%8,%%!Bxd53!Bwg(Y!Bxg(Y!^wd(Y!^xd(Y!^wg(Y!^xg(Y!At\
m(Y!Aum(Y!Atp(Y!Aup(Y!]tm(Y!]um(Y!]tp(Y!]up(Y!Btm(W",
"%%%%%/%Yh00,,8%&D8,,%E%D&%8,%%!6Vh.c!Buh(Y!Btq(Y!Buq(Y!^th(Y!^uh(Y!^tq(Y!^u\
q(Y!Awh(Y!Axh(Y!Awq(Y!Axq(Y!]wh(Y!]xh(Y!]wq(Y!]xq(Y!B<h({",
"%%%%%/8Yh00,,8%&D8,,%E%D(%8,%%!.^<b<]!.^Yb(Y!.^=b(Y!.^Zb(Y!7^<b(Y!7^Yb(Y!7^\
=b(Y!7^Zb(Y!LA8b(Y!LAVb(Y!LA9b(Y!LAWb(Y!UA8b(Y!UAVb(Y!UA9b(Y!UAWb(Y",
"%%%%%//Yh00,,8%&D8,,%E%D%%8,%%!Bth(Y!Buh(Y!Btq(Y!Buq(Y!^th(Y!^uh(Y!^tq(Y!^u\
q(Y!Awh(Y!Axh(Y!Awq(Y!Axq(Y!]wh(Y!]xh(Y!]wq(Y!]xq(V",
"%%%%%//Yh00,,8%&D8,,%E%D(%8,%%!]Zg5<!Bwd(Y!Bxd(Y!Bwg(Y!Bxg(Y!^wd(Y!^xd(Y!^w\
g(Y!^xg(Y!Atm(Y!Aum(Y!Atp(Y!Aup(Y!]tm(Y!]um(Y!]tp(Y!J9p.c",
"%%%%%//Yh00,,8%&D8,,%E%D&%8,%%!]uq<V!Bth(Y!Buh(Y!Btq(Y!Buq(Y!^th(Y!^uh(Y!^t\
q(Y!^uq(Y!Awh(Y!Axh(Y!Awq(Y!Axq(Y!]wh(Y!]xh(Y!]wq(X",
"%%%%%k8Yh09,,8%(D8,,%E%b(%8,%%!3lnoD-b!4moob(Y!1pnnb(Y!1ponb(Y!1pnob(Y!1poo\
b(Y!4pnnb(Y!4ponb(Y!4pnob(Y!4poob(Y!Fdbbb(Y!Fdcbb(Y!Fdbcb(Y!Fdccb(Y!Idbbb(Y!\
Idcbb(Y!Ibbcb(}",
"%%%%%M%Yh0&,,8%%D8,,%E%%%%8,%%!]Vq(}!]uq(Y!Bth(Y!Buh(Y!Btq(Y!Buq(Y!^th(Y!^u\
h(Y!^tq(Y!^uq(Y!Awh(Y!Axh(Y!Awq(Y!Axq(Y!]wh(Y!]xh(Y!J<k-b",
"%%%%%M%Yh0&,,8%%D8,,%E%%(%8,%%!]wg53!]xg(Y!Bwd(Y!Bxd(Y!Bwg(Y!Bxg(Y!^wd(Y!^x\
d(Y!^wg(Y!^xg(Y!Atm(Y!Aum(Y!Atp(Y!Aup(Y!]tm(Y!]um(W",
"%%%%%M%Yh0&,,8%%D8,,%E%%&%8,%%!SWh.c!]tq(Y!]uq(Y!Bth(Y!Buh(Y!Btq(Y!Buq(Y!^t\
h(Y!^uh(Y!^tq(Y!^uq(Y!Awh(Y!Axh(Y!Awq(Y!Axq(Y!]wh(Y!]=h({",
"%%%%%M8Yh0&,,8%%D8,,%E%%(%8,%%!7BYb<]!7B=b(Y!7BZb(Y!.^<b(Y!.^Yb(Y!.^=b(Y!.^\
Zb(Y!7^<b(Y!7^Yb(Y!7^=b(Y!7^Zb(Y!LA8b(Y!LAVb(Y!LA9b(Y!LAWb(Y!UA8b(Y",
"%%%%%M/Yh0&,,8%%D8,,%E%%%%8,%%!]uh(Y!]tq(Y!]uq(Y!Bth(Y!Buh(Y!Btq(Y!Buq(Y!^t\
h(Y!^uh(Y!^tq(Y!^uq(Y!Awh(Y!Axh(Y!Awq(Y!Axq(Y!]wh(V",
"%%%%%M/Yh0&,,8%%D8,,%E%%(%8,%%!]Yd5<!]xd(Y!]wg(Y!]xg(Y!Bwd(Y!Bxd(Y!Bwg(Y!Bx\
g(Y!^wd(Y!^xd(Y!^wg(Y!^xg(Y!Atm(Y!Aum(Y!Atp(Y!Aup(Y!J8m.c",
"%%%%%M/Yh0&,,8%%D8,,%E%%&%8,%%!]th<V!]uh(Y!]tq(Y!]uq(Y!Bth(Y!Buh(Y!Btq(Y!Bu\
q(Y!^th(Y!^uh(Y!^tq(Y!^uq(Y!Awh(Y!Axh(Y!Awq(Y!Axq(X",
"%%%%%M8Yh09,,8%%D8,,%E%%(%8,%%!I+TM-b!U.K8(Y!U.T8(Y!U.KV(Y!U.TV(Y!L7K8(Y!L7\
T8(Y!L7KV(Y!L7TV(Y!U7K8(Y!U7T8(Y!U7KV(Y!U7TV(Y!.L,8(Y!.L58(Y!.L,V(Y!.F5V(}",
"%%%%%M%Yh00,,8%%D8,,%E%%%%8,%%!AWq(}!]th(Y!]uh(Y!]tq(Y!]uq(Y!Bth(Y!Buh(Y!Bt\
q(Y!Buq(Y!^th(Y!^uh(Y!^tq(Y!^uq(Y!Awh(Y!Axh(Y!Awq(Y!,=k-b",
"%%%%%M%Yh00,,8%%D8,,%E%%(%8,%%!Axg53!]wd(Y!]xd(Y!]wg(Y!]xg(Y!Bwd(Y!Bxd(Y!Bw\
g(Y!Bxg(Y!^wd(Y!^xd(Y!^wg(Y!^xg(Y!Atm(Y!Aum(Y!Atp(W",
"%%%%%M%Yh00,,8%%D8,,%E%%&%8,%%!5Vq.c!Auq(Y!]th(Y!]uh(Y!]tq(Y!]uq(Y!Bth(Y!Bu\
h(Y!Btq(Y!Buq(Y!^th(Y!^uh(Y!^tq(Y!^uq(Y!Awh(Y!Axh(Y!A<q({",
"%%%%%M8Yh00,,8%%D8,,%E%%(%8,%%!.B=b<]!.BZb(Y!7B<b(Y!7BYb(Y!7B=b(Y!7BZb(Y!.^\
<b(Y!.^Yb(Y!.^=b(Y!.^Zb(Y!7^<b(Y!7^Yb(Y!7^=b(Y!7^Zb(Y!LA8b(Y!LAVb(Y",
"%%%%%M/Yh00,,8%%D8,,%E%%%%8,%%!Atq(Y!Auq(Y!]th(Y!]uh(Y!]tq(Y!]uq(Y!Bth(Y!Bu\
h(Y!Btq(Y!Buq(Y!^th(Y!^uh(Y!^tq(Y!^uq(Y!Awh(Y!Axh(V",
"%%%%%M/Yh00,,8%%D8,,%E%%(%8,%%!AZd5<!Awg(Y!Axg(Y!]wd(Y!]xd(Y!]wg(Y!]xg(Y!Bw\
d(Y!Bxd(Y!Bwg(Y!Bxg(Y!^wd(Y!^xd(Y!^wg(Y!^xg(Y!Atm(Y!,9m.c",
"%%%%%M/Yh00,,8%%D8,,%E%%&%8,%%!Auh<V!Atq(Y!Auq(Y!]th(Y!]uh(Y!]tq(Y!]uq(Y!Bt\
h(Y!Buh(Y!Btq(Y!Buq(Y!^th(Y!^uh(Y!^tq(Y!^uq(Y!Awh(X",
"%%%%%M8Yh09,,8%(D8,,%E%%(%8,%%!II1G-b!LL4J(Y!LL1S(Y!LL4S(Y!UL1J(Y!UL4J(Y!UL\
1S(Y!UL4S(Y!LU1J(Y!LU4J(Y!LU1S(Y!LU4S(Y!UU1J(Y!UU4J(Y!UU1S(Y!UU4S(Y!.(F,(}",
"%%%%%M%Yh0&,,8%&D8,,%E%%%%8,%%!AVh(}!Auh(Y!Atq(Y!Auq(Y!]th(Y!]uh(Y!]tq(Y!]u\
q(Y!Bth(Y!Buh(Y!Btq(Y!Buq(Y!^th(Y!^uh(Y!^tq(Y!^uq(Y!,<b-b",
"%%%%%M%Yh0&,,8%&D/,,%E%%%%8,%%!Av853!Ay8(Y!AvV(Y!AyV(Y!]v8(Y!]y8(Y!]vV(Y!]y\
V(Y!Bv8(Y!By8(Y!BvV(Y!ByV(Y!^v8(Y!^y8(Y!^vV(Y!^yV(W",
"%%%%%M%Yh0&,,8%&D8,,%E%%(%8,%%!TZg.c!Atm(Y!Aum(Y!Atp(Y!Aup(Y!]tm(Y!]um(Y!]t\
p(Y!]up(Y!Btm(Y!Bum(Y!Btp(Y!Bup(Y!^tm(Y!^um(Y!^tp(Y!^9p({",
"%%%%%M%Yh0&,,8%&D8,,%E%%&%8,%%!^uq<]!Awh(Y!Axh(Y!Awq(Y!Axq(Y!]wh(Y!]xh(Y!]w\
q(Y!]xq(Y!Bwh(Y!Bxh(Y!Bwq(Y!Bxq(Y!^wh(Y!^xh(Y!^wq(Y",
"%%%%%M8Yh0&,,8%&D8,,%E%%(%8,%%!7^Zb(Y!LA8b(Y!LAVb(Y!LA9b(Y!LAWb(Y!UA8b(Y!UA\
Vb(Y!UA9b(Y!UAWb(Y!L]8b(Y!L]Vb(Y!L]9b(Y!L]Wb(Y!U]8b(Y!U]Vb(Y!U]9b(V",
"%%%%%M/Yh0&,,8%&D8,,%E%%%%8,%%!^Vq5<!^uq(Y!Awh(Y!Axh(Y!Awq(Y!Axq(Y!]wh(Y!]x\
h(Y!]wq(Y!]xq(Y!Bwh(Y!Bxh(Y!Bwq(Y!Bxq(Y!^wh(Y!^xh(Y!K<q.c",
"%%%%%M/Yh0&,,8%&D8,,%E%%(%8,%%!^wg<V!^xg(Y!Atm(Y!Aum(Y!Atp(Y!Aup(Y!]tm(Y!]u\
m(Y!]tp(Y!]up(Y!Btm(Y!Bum(Y!Btp(Y!Bup(Y!^tm(Y!^um(X",
"%%%%%M/Yh0&,,8%&D8,,%E%%&%8,%%!TWe-b!^tq(Y!^uq(Y!Awh(Y!Axh(Y!Awq(Y!Axq(Y!]w\
h(Y!]xh(Y!]wq(Y!]xq(Y!Bwh(Y!Bxh(Y!Bwq(Y!Bxq(Y!^wh(Y!^=h(}",
"%%%%%M8Yh09,,8%&D8,,%E%%(%8,%%!U4T8(}!U7KV(Y!U7TV(Y!.L,8(Y!.L58(Y!.L,V(Y!.L\
5V(Y!7L,8(Y!7L58(Y!7L,V(Y!7L5V(Y!.U,8(Y!.U58(Y!.U,V(Y!.U5V(Y!7U,8(Y!1O5%-b",
"%%%%%M%Yh00,,8%&D8,,%E%%%%8,%%!^uh53!^tq(Y!^uq(Y!Awh(Y!Axh(Y!Awq(Y!Axq(Y!]w\
h(Y!]xh(Y!]wq(Y!]xq(Y!Bwh(Y!Bxh(Y!Bwq(Y!Bxq(Y!^wh(W",
"%%%%%M%Yh00,,8%&D8,,%E%%(%8,%%!TYd.c!^xd(Y!^wg(Y!^xg(Y!Atm(Y!Aum(Y!Atp(Y!Au\
p(Y!]tm(Y!]um(Y!]tp(Y!]up(Y!Btm(Y!Bum(Y!Btp(Y!Bup(Y!^8m({",
"%%%%%M%Yh00,,8%&D8,,%E%%&%8,%%!^th<]!^uh(Y!^tq(Y!^uq(Y!Awh(Y!Axh(Y!Awq(Y!Ax\
q(Y!]wh(Y!]xh(Y!]wq(Y!]xq(Y!Bwh(Y!Bxh(Y!Bwq(Y!Bxq(Y",
"%%%%%M8Yh00,,8%&D8,,%E%%(%8,%%!7^<b(Y!7^Yb(Y!7^=b(Y!7^Zb(Y!LA8b(Y!LAVb(Y!LA\
9b(Y!LAWb(Y!UA8b(Y!UAVb(Y!UA9b(Y!UAWb(Y!L]8b(Y!L]Vb(Y!L]9b(Y!L]Wb(V",
"%%%%%M/Yh00,,8%&D8,,%E%%%%8,%%!BWq5<!^th(Y!^uh(Y!^tq(Y!^uq(Y!Awh(Y!Axh(Y!Aw\
q(Y!Axq(Y!]wh(Y!]xh(Y!]wq(Y!]xq(Y!Bwh(Y!Bxh(Y!Bwq(Y!-=q.c",
"%%%%%M/Yh00,,8%&D8,,%E%%(%8,%%!Bxg<V!^wd(Y!^xd(Y!^wg(Y!^xg(Y!Atm(Y!Aum(Y!At\
p(Y!Aup(Y!]tm(Y!]um(Y!]tp(Y!]up(Y!Btm(Y!Bum(Y!Btp(X",
"%%%%%M/Yh00,,8%&D8,,%E%%&%8,%%!6Vn-b!Buq(Y!^th(Y!^uh(Y!^tq(Y!^uq(Y!Awh(Y!Ax\
h(Y!Awq(Y!Axq(Y!]wh(Y!]xh(Y!]wq(Y!]xq(Y!Bwh(Y!Bxh(Y!B<q(}",
"%%%%%M8Yh09,,8%(D8,,%E%b(%8,%%!LRO4(}!LUR4(Y!UUO1(Y!UUR1(Y!UUO4(Y!UUR4(Y!..\
(F(Y!..+F(Y!..(I(Y!..+I(Y!7.(F(Y!7.+F(Y!7.(I(Y!7.+I(Y!.7(F(Y!.7+F(Y!(1(G-b",
"%%%%%M%Yh0&,,8%%D8,,%E%D%%8,%%!Btq53!Buq(Y!^th(Y!^uh(Y!^tq(Y!^uq(Y!Awh(Y!Ax\
h(Y!Awq(Y!Axq(Y!]wh(Y!]xh(Y!]wq(Y!]xq(Y!Bwh(Y!Bxh(W",
"%%%%%M%Yh0&,,8%%D8,,%E%D(%8,%%!6Zd.c!Bwg(Y!Bxg(Y!^wd(Y!^xd(Y!^wg(Y!^xg(Y!At\
m(Y!Aum(Y!Atp(Y!Aup(Y!]tm(Y!]um(Y!]tp(Y!]up(Y!Btm(Y!B9m({",
"%%%%%M%Yh0&,,8%%D8,,%E%D&%8,%%!Buh<]!Btq(Y!Buq(Y!^th(Y!^uh(Y!^tq(Y!^uq(Y!Aw\
h(Y!Axh(Y!Awq(Y!Axq(Y!]wh(Y!]xh(Y!]wq(Y!]xq(Y!Bwh(Y",
"%%%%%M8Yh0&,,8%%D8,,%E%D(%8,%%!.^Yb(Y!.^=b(Y!.^Zb(Y!7^<b(Y!7^Yb(Y!7^=b(Y!7^\
Zb(Y!LA8b(Y!LAVb(Y!LA9b(Y!LAWb(Y!UA8b(Y!UAVb(Y!UA9b(Y!UAWb(Y!L]8b(V",
"%%%%%M/Yh0&,,8%%D8,,%E%D%%8,%%!BVh5<!Buh(Y!Btq(Y!Buq(Y!^th(Y!^uh(Y!^tq(Y!^u\
q(Y!Awh(Y!Axh(Y!Awq(Y!Axq(Y!]wh(Y!]xh(Y!]wq(Y!]xq(Y!-<h.c",
"%%%%%M/Yh0&,,8%%D8,,%E%D(%8,%%!Bwd<V!Bxd(Y!Bwg(Y!Bxg(Y!^wd(Y!^xd(Y!^wg(Y!^x\
g(Y!Atm(Y!Aum(Y!Atp(Y!Aup(Y!]tm(Y!]um(Y!]tp(Y!]up(X",
"%%%%%M/Yh0&,,8%%D8,,%E%D&%8,%%!SWn-b!Bth(Y!Buh(Y!Btq(Y!Buq(Y!^th(Y!^uh(Y!^t\
q(Y!^uq(Y!Awh(Y!Axh(Y!Awq(Y!Axq(Y!]wh(Y!]xh(Y!]wq(Y!]=q(}",
"%%%%%M8Yh09,,8%%D8,,%E%D(%8,%%!U+TV(}!L7K8(Y!L7T8(Y!L7KV(Y!L7TV(Y!U7K8(Y!U7\
T8(Y!U7KV(Y!U7TV(Y!.L,8(Y!.L58(Y!.L,V(Y!.L5V(Y!7L,8(Y!7L58(Y!7L,V(Y!1F5D-b",
"%%%%%M%Yh00,,8%%D8,,%E%D%%8,%%!]uq53!Bth(Y!Buh(Y!Btq(Y!Buq(Y!^th(Y!^uh(Y!^t\
q(Y!^uq(Y!Awh(Y!Axh(Y!Awq(Y!Axq(Y!]wh(Y!]xh(Y!]wq(W",
"%%%%%M%Yh00,,8%%D8,,%E%D(%8,%%!SYg.c!]xg(Y!Bwd(Y!Bxd(Y!Bwg(Y!Bxg(Y!^wd(Y!^x\
d(Y!^wg(Y!^xg(Y!Atm(Y!Aum(Y!Atp(Y!Aup(Y!]tm(Y!]um(Y!]8p({",
"%%%%%M%Yh00,,8%%D8,,%E%D&%8,%%!]tq<]!]uq(Y!Bth(Y!Buh(Y!Btq(Y!Buq(Y!^th(Y!^u\
h(Y!^tq(Y!^uq(Y!Awh(Y!Axh(Y!Awq(Y!Axq(Y!]wh(Y!]xh(Y",
"%%%%%M8Yh00,,8%%D8,,%E%D(%8,%%!7B=b(Y!7BZb(Y!.^<b(Y!.^Yb(Y!.^=b(Y!.^Zb(Y!7^\
<b(Y!7^Yb(Y!7^=b(Y!7^Zb(Y!LA8b(Y!LAVb(Y!LA9b(Y!LAWb(Y!UA8b(Y!UAVb(V",
"%%%%%M/Yh00,,8%%D8,,%E%D%%8,%%!]Wh5<!]tq(Y!]uq(Y!Bth(Y!Buh(Y!Btq(Y!Buq(Y!^t\
h(Y!^uh(Y!^tq(Y!^uq(Y!Awh(Y!Axh(Y!Awq(Y!Axq(Y!]wh(Y!J=h.c",
"%%%%%M/Yh00,,8%%D8,,%E%D(%8,%%!]xd<V!]wg(Y!]xg(Y!Bwd(Y!Bxd(Y!Bwg(Y!Bxg(Y!^w\
d(Y!^xd(Y!^wg(Y!^xg(Y!Atm(Y!Aum(Y!Atp(Y!Aup(Y!]tm(X",
"%%%%%M/Yh00,,8%%D8,,%E%D&%8,%%!SVe-b!]uh(Y!]tq(Y!]uq(Y!Bth(Y!Buh(Y!Btq(Y!Bu\
q(Y!^th(Y!^uh(Y!^tq(Y!^uq(Y!Awh(Y!Axh(Y!Awq(Y!Axq(Y!]<h(}",
"%%%%%M8Yh09,,8%(D8,,%E%D(%8,%%!UI1J(}!UL4J(Y!UL1S(Y!UL4S(Y!LU1J(Y!LU4J(Y!LU\
1S(Y!LU4S(Y!UU1J(Y!UU4J(Y!UU1S(Y!UU4S(Y!..F,(Y!..I,(Y!..F5(Y!..I5(Y!1(F%-b",
"%%%%%M%Yh0&,,8%&D8,,%E%D%%8,%%!]th53!]uh(Y!]tq(Y!]uq(Y!Bth(Y!Buh(Y!Btq(Y!Bu\
q(Y!^th(Y!^uh(Y!^tq(Y!^uq(Y!Awh(Y!Axh(Y!Awq(Y!Axq(W",
"%%%%%M%Yh0&,,8%&D8,,%E%D(%8,%%!5Zg.c!]wd(Y!]xd(Y!]wg(Y!]xg(Y!Bwd(Y!Bxd(Y!Bw\
g(Y!Bxg(Y!^wd(Y!^xd(Y!^wg(Y!^xg(Y!Atm(Y!Aum(Y!Atp(Y!A9p({",
"%%%%%M%Yh0&,,8%&D8,,%E%D&%8,%%!Auq<]!]th(Y!]uh(Y!]tq(Y!]uq(Y!Bth(Y!Buh(Y!Bt\
q(Y!Buq(Y!^th(Y!^uh(Y!^tq(Y!^uq(Y!Awh(Y!Axh(Y!Awq(Y",
"%%%%%M8Yh0&,,8%&D8,,%E%D(%8,%%!.BZb(Y!7B<b(Y!7BYb(Y!7B=b(Y!7BZb(Y!.^<b(Y!.^\
Yb(Y!.^=b(Y!.^Zb(Y!7^<b(Y!7^Yb(Y!7^=b(Y!7^Zb(Y!LA8b(Y!LAVb(Y!LA9b(V",
"%%%%%M/Yh0&,,8%&D8,,%E%D%%8,%%!AVq5<!Auq(Y!]th(Y!]uh(Y!]tq(Y!]uq(Y!Bth(Y!Bu\
h(Y!Btq(Y!Buq(Y!^th(Y!^uh(Y!^tq(Y!^uq(Y!Awh(Y!Axh(Y!,<q.c",
"%%%%%M/Yh0&,,8%&D8,,%E%D(%8,%%!Awg<V!Axg(Y!]wd(Y!]xd(Y!]wg(Y!]xg(Y!Bwd(Y!Bx\
d(Y!Bwg(Y!Bxg(Y!^wd(Y!^xd(Y!^wg(Y!^xg(Y!Atm(Y!Aum(X",
"%%%%%M/Yh0&,,8%&D8,,%E%D&%8,%%!5We-b!Atq(Y!Auq(Y!]th(Y!]uh(Y!]tq(Y!]uq(Y!Bt\
h(Y!Buh(Y!Btq(Y!Buq(Y!^th(Y!^uh(Y!^tq(Y!^uq(Y!Awh(Y!A=h(}",
"%%%%%M8Yh09,,8%&D8,,%E%D(%8,%%!L+T8(}!L.KV(Y!L.TV(Y!U.K8(Y!U.T8(Y!U.KV(Y!U.\
TV(Y!L7K8(Y!L7T8(Y!L7KV(Y!L7TV(Y!U7K8(Y!U7T8(Y!U7KV(Y!U7TV(Y!.L,8(Y!(F5%-b" ];
