#############################################################################
##
#W  grppc.gd                    GAP Library                      Frank Celler
##
#H  @(#)$Id$
##
#Y  Copyright (C)  1996,  Lehrstuhl D fuer Mathematik,  RWTH Aachen,  Germany
##
##  This file contains the operations for groups with a polycyclic collector.
##
##  IsPcgs
##    a polycyclic generating system, also behaves like a pc sequence
##
##  IsPcGroup
##    a poylcyclic group whose elements family is defined by a collector
##
##  IsPcgsComputable
##    a group that knows how to compute a pcgs relatively fast
##
##  HasDefiningPcgs
##    a group whose elements family is generated by a pcgs
##
##  HasHomePcgs
##    a group that knows a pcgs of a super group
##
Revision.grppc_gd :=
    "@(#)$Id$";

InfoPcGroup:=NewInfoClass("InfoPcGroup");


#############################################################################
##

#A  CanonicalPcgsWrtFamilyPcgs( <grp> )	. . . . . . .  with respect to family
##
CanonicalPcgsWrtFamilyPcgs := NewAttribute(
    "CanonicalPcgsWrtFamilyPcgs",
    IsGroup );

SetCanonicalPcgsWrtFamilyPcgs := Setter(CanonicalPcgsWrtFamilyPcgs);
HasCanonicalPcgsWrtFamilyPcgs := Tester(CanonicalPcgsWrtFamilyPcgs);


#############################################################################
##
#A  CanonicalPcgsWrtHomePcgs( <grp> ) . . . . . . . . .  with respect to home
##
CanonicalPcgsWrtHomePcgs := NewAttribute(
    "CanonicalPcgsWrtHomePcgs",
    IsGroup );

SetCanonicalPcgsWrtHomePcgs := Setter(CanonicalPcgsWrtHomePcgs);
HasCanonicalPcgsWrtHomePcgs := Tester(CanonicalPcgsWrtHomePcgs);


#############################################################################
##
#A  FamilyPcgs( <grp> ) . . . . . . . . . . . . . . . . .  pcgs of the family
##
FamilyPcgs := NewAttribute(
    "FamilyPcgs",
    IsGroup );

SetFamilyPcgs := Setter(FamilyPcgs);
HasFamilyPcgs := Tester(FamilyPcgs);

InstallSubsetMaintainedMethod( FamilyPcgs, IsGroup, IsGroup );


#############################################################################
##
#A  HomePcgs( <grp> ) . . . . . . . . . . . . . . . . . . .  pcgs of the home
##
HomePcgs := NewAttribute(
    "HomePcgs",
    IsGroup );

SetHomePcgs := Setter(HomePcgs);
HasHomePcgs := Tester(HomePcgs);

InstallSubsetMaintainedMethod( HomePcgs, IsGroup, IsGroup );


#############################################################################
##
#A  InducedPcgsWrtFamilyPcgs( <grp> ) . . . . . . . .  with respect to family
##
InducedPcgsWrtFamilyPcgs := NewAttribute(
    "InducedPcgsWrtFamilyPcgs",
    IsGroup );

SetInducedPcgsWrtFamilyPcgs := Setter(InducedPcgsWrtFamilyPcgs);
HasInducedPcgsWrtFamilyPcgs := Tester(InducedPcgsWrtFamilyPcgs);


#############################################################################
##
#A  InducedPcgsWrtHomePcgs( <grp> ) . . . . . . . . . .  with respect to home
##
InducedPcgsWrtHomePcgs := NewAttribute(
    "InducedPcgsWrtHomePcgs",
    IsGroup );

SetInducedPcgsWrtHomePcgs := Setter(InducedPcgsWrtHomePcgs);
HasInducedPcgsWrtHomePcgs := Tester(InducedPcgsWrtHomePcgs);


#############################################################################
##
#A  Pcgs( <grp> ) . . . . . . . . . . . . . . . . . . . . . . pcgs of a group
##
Pcgs := NewAttribute(
    "Pcgs",
    IsGroup );

SetPcgs := Setter( Pcgs );
HasPcgs := Tester( Pcgs );


#############################################################################
##

#P  IsPcgsComputable( <grp> ) . . . . . . .  group is willing to compute pcgs
##
IsPcgsComputable := NewProperty(
    "IsPcgsComputable",
    IsGroup );

SetIsPcgsComputable := Setter(IsPcgsComputable);
HasIsPcgsComputable := Tester(IsPcgsComputable);


#############################################################################
##
#M  IsPcgsComputable( <pcgrp> ) . . . . . . . . . . . . . . . . . .  pc group
##
InstallTrueMethod(
    IsPcgsComputable,
    IsPcGroup );

InstallTrueMethod(
    IsPcgsComputable,
    HasPcgs );


#############################################################################
##
#M  IsPcgsComputable( <grp> ) . . . . . . . . . . . home or family pcgs known
##
InstallTrueMethod( IsPcgsComputable, IsGroup and HasHomePcgs );
InstallTrueMethod( IsPcgsComputable, IsGroup and HasFamilyPcgs );


#############################################################################
##

#O  SubgroupByPcgs( <G>, <pcgs> )
##
SubgroupByPcgs := NewOperation( "SubgroupByPcgs", [IsGroup, IsPcgs] );


#############################################################################
##
#O  AffineOperation( <gens>, <basisvectors>, <linear>, <transl> )
##
AffineOperation := NewOperation(
    "AffineOperation", 
    [ IsList, IsMatrix, IsFunction, IsFunction ] );


#############################################################################
##
#O  LinearOperation( <gens>, <basisvectors>, <linear> )
##
LinearOperation := NewOperation(
    "LinearOperation",
    [ IsList, IsMatrix, IsFunction ] );


#############################################################################
##
#M  IsSolvableGroup
##
InstallTrueMethod(
    IsSolvableGroup,
    IsPcGroup );


#############################################################################
##
#F  AffineOperationLayer( <G>, <gens>, <pcgs>, <transl> )
##
AffineOperationLayer := NewOperationArgs( "AffineOperationLayer" );


#############################################################################
##
#F  GeneratorsCentrePGroup( <G> )
##
GeneratorsCentrePGroup := NewOperationArgs( "GeneratorsCentrePGroup" );


#############################################################################
##
#F  LinearOperationLayer( <G>, <gens>, <pcgs> )
##
LinearOperationLayer := NewOperationArgs( "LinearOperationLayer" );


#############################################################################
##
#F  VectorSpaceByPcgsOfElementaryAbelianGroup( <pcgs>, <fld> )
##
VectorSpaceByPcgsOfElementaryAbelianGroup := NewOperationArgs(
    "VectorSpaceByPcgsOfElementaryAbelianGroup" );

#############################################################################
##
#F  GapInputPcGroup( <grp>, <string> )
##
GapInputPcGroup := NewOperationArgs( "GapInputPcGroup" );

#############################################################################
##
#O  CanonicalSubgroupRepresentativePcGroup( <G>, <U> )
##
CanonicalSubgroupRepresentativePcGroup :=
  NewOperationArgs( "CanonicalSubgroupRepresentativePcGroup" );


#############################################################################
##
#A  OmegaSeries( G )
##
OmegaSeries := NewAttribute( "OmegaSeries", IsGroup );

#############################################################################
##

#E  grppc.gd  . . . . . . . . . . . . . . . . . . . . . . . . . . . ends here
##
