VERSION := "current";
DATE := "current";
P("");
P("ALPHA ALPHA ALPHA ALPHA ALPHA ALPHA ALPHA ALPHA ALPHA ALPHA ALPHA ALPHA");
P("");
P("This is  an ALPHA version  of GAP 4.  Please  do not  redistribute this");
P("version, discuss it  in the  GAP forum,  or use  it  for more  than two");
P("weeks.  You can get a new version from");
P("");
P("                ftp://ftp.math.rwth-aachen.de");
P("");
P("Please report bugs and problems to");
P("");
P("                  gap-trouble@dcs.st-and.ac.uk");
P("");
P("quoting the Version and Date below and the machine, operation system,");
P("and compiler used.");
P("");
P("ALPHA ALPHA ALPHA ALPHA ALPHA ALPHA ALPHA ALPHA ALPHA ALPHA ALPHA ALPHA");
P("");
Print("Version:  ", VERSION, "\n");
Print("Date:     ", DATE, "\n");
P("");
P("ALPHA ALPHA ALPHA ALPHA ALPHA ALPHA ALPHA ALPHA ALPHA ALPHA ALPHA ALPHA");
P("");
P("Loading the library, please be patient this may take a while.");
P("");
