#############################################################################
##
#W kantin.gd            Alnuth -  Kant interface                 Bettina Eick
#W                                                             Bjoern Assmann
#W                                                            Andreas Distler
##

#############################################################################
##
#F  PolynomialFactorsDescriptionKant, function( <poly>, <f>)
##
##  Factorizes the polynomial <poly> in the field generated by <f>
##  with KANT
##
DeclareGlobalFunction( "PolynomialFactorsDescriptionKant" );

#############################################################################
##
#F TestKantExecutable( path )
##
DeclareGlobalFunction( "TestKantExecutable" );

#############################################################################
##
#F SetKantExecutable( path )
##
## Sets the variable KANTEXEC
##
DeclareGlobalFunction( "SetKantExecutable" );

#############################################################################
##
#F SetKantExecutablePermanently( path )
##
## Changes the file defs.g to set a new standard value for KANTEXEC
##
DeclareGlobalFunction( "SetKantExecutablePermanently" );
                                                                       
#############################################################################
##
#E
                                                                               


