---------------------------------------------------------------
Construction of Finitely Presented Lie SuperAlgebras. Version 4
                        April 15, 1997
                  V.P. Gerdt and V.V. Kornyak
---------------------------------------------------------------
$
Enter name of existing or new input file -> $
 $
File doesn't exist. Create new file? (y/n) -> $
Enter generator symbols ->
$
Enter weights of generators ->
$
Enter limiting weight -> $
Enter scalar parameters ->
$
Enter defining relations ->
$
Input data:
$
Initial relations:

$
Non-zero parametric coefficients:

$
Reduced relations:

$
Basis elements:

$
Hilbert series:

$
Non-zero commutators of basis elements:

$
*** There are no non-zero commutators

$
Error:
$
File FPLSA4.INI contains wrong case
$
Input file contains wrong item
$
The program is cancelled
$
Unexpected end of initiating or input file
$
Can not allocate GeneratorName string
$
Can not allocate ParameterName string
$
Can not allocate OutLine string
$
Can not allocate Relation array
$
Can not allocate LieMonomial table
$
Can not allocate NodeLT pool for Lie terms
$
Can not allocate NodeST pool for scalar terms
$
Can not allocate NodeSF pool for scalar factors
$
Can not allocate integer in heap memory
$
Can not allocate CoeffParamTable for single non-zero parameters
$
Can not allocate CoeffSumTable for non-zero parametric polynomials
$
Heap memory allocation error
$
Can not allocate in stack string for reading input
$
Can not allocate in stack working integer
$
Can not allocate in stack decimal string for integer
$
Can not allocate in stack working array for polynomials
$
Increase "Input string size" in file FPLSA4.INI
$
Increase "OutLine size" in file FPLSA4.INI
$
Increase "Lie monomial table size" in file FPLSA4.INI
$
Increase "Relation size" in file FPLSA4.INI
$
Increase "Node Lie term size" in file FPLSA4.INI
$
Increase "Node scalar factor size" in file FPLSA4.INI
$
Increase "Node scalar term size" in file FPLSA4.INI
$
Increase "Coefficient sum table size" in file FPLSA4.INI
$
Increase "Generator max. number" in file FPLSA4.INI
$
Increase "Parameter max. number" in file FPLSA4.INI
$
Number of input weights exceeds number of generators
$
Only positive integer weights for generators are allowed
$
Right parenthesis is needed
$
Only positive integer degrees of parameters are implemented
$
Undeclared generator
$
No comma in Lie bracket
$
No closing Lie bracket
$
Invalid character
$
Message file does not contain required message
$
