#!/bin/sh
#############################################################################
##
#W  compile							 Frank Celler
##
##  this shell script compiles the next version of the betbeta release
##
if [ -z "$BINDIR" ];  then
    echo "PANIC: you must set 'BINDIR'"
    exit 1
fi
if ${BINDIR}/checkvar;  then echo;  else
    exit 1
fi


# go into the source directoy and compile
cd ${BETAROOT}/${BETANAME}/src
echo "$0: compiling version $VERSION of $DATE for $MAKETARGET"
make ${MAKETARGET}


# check that a executable has been created
if [ \! -x ${GAPEXEC} ];  then
    echo "PANIC: no executable '${GAPEXEC}' has been created"
    exit 1
fi

echo "============================================================="
echo "Creating completion files"
echo "CreateCompletionFiles();quit;" | ${GAPEXEC} -l ${BETAROOT}/${BETANAME} -N

exit 0
