#!/bin/bash 

echo ""
echo "Start this script from a copy of GAPDoc within the GAP root you want"
echo "to use for compiling the documentation. Also,"
echo "did you adjust (yN)?: Version, Date, ArchiveURL in ./PackageInfo.g"
echo "                ./version"
echo "                Date. copyright date, Version in doc/gapdoc.xml"
echo "                                                 example/example.xml"
echo ""
read -n 1 start
echo
if [ $start'X' != 'yX' ]; then
  echo Ok, please adjust and try again.
  exit 2
fi

dirnam=GAPDoc-`cat ./version`
rm -rf ttttmp
echo "Checking out current version into ttttmp/pkg/"$dirnam" . . ."
mkdir -p ttttmp/pkg/$dirnam
cd ttttmp/pkg/$dirnam
cp -a ../../../.git .
git co master .
echo building documentation
../../../../../bin/gap.sh -r -l "../..;" < makedocrel.g > /dev/null


echo "removing unwanted files . . ."
rm -r pack TODO clean index.html pkgreadme.css
rm -rf .git .gitignore
rm -rf */*.{log,aux,blg,brf,bbl,idx,ilg,ind,pnr} */*.xml.bib */.cvsignore
rm -f ./makedoc.g ./maketxt ./doku toweb

echo "creating archive . . ."
cd ..
tar cf $dirnam.tar $dirnam
bzip2 -9 $dirnam.tar
echo Cleaning up
mv  $dirnam.tar.bz2 ../..
cd ../..
rm -rf ttttmp

echo New archive in ./$dirnam.tar.bz2
echo If ok then call
echo "      ~/gap4/dev/DistributionUpdate/maindist/repack.py "$dirnam".tar.bz2"

echo "If you are happy with this archive 
#tag the current state before"
#echo "committing further changes, e.g.: "
#echo "       cvs tag REL"`sed -e "s/\./_/g" version`
echo "use the ./toweb script to update the webpage."
echo "Then change version number back to '1.dev'."

