#!/bin/sh
#############################################################################
##
#W  maketoc              GAP 4 package AtlasRep                 Thomas Breuer
##
#Y  Copyright (C)  2001,  Lehrstuhl D fuer Mathematik,  RWTH Aachen,  Germany
##
##  This script fetches the newest version of the file
##  'pkg/atlasrep/gap/atlasprm.g' from the package's homepage,
##  replaces the package's file with it if necessary, and saves the old
##  version of that file in 'pkg/atlasrep/gap/atlasprm.old'.
##
##  The script must be called from the directory 'pkg/atlasrep',
##  in the form `etc/maketoc <gap>',
##  where <gap> must be a command to call GAP 4.
##
$1 -q <<EOF
LoadPackage( "atlasrep" );
dstdir:= DirectoriesPackageLibrary( "atlasrep", "gap" );
dstfile:= Filename( dstdir, "atlasprm.g" );
if IsWritableFile( dstfile ) then
  AtlasOfGroupRepresentationsUpdateTableOfContentsFile( dstfile );
fi;
quit;
EOF


#############################################################################
##
#E

