#!/bin/sh
#############################################################################
##
#W  mktest           Test the CRYST manual examples            Volkmar Felsch
##
#H  $Id: mktest,v 1.2 2002/08/30 06:53:34 gap Exp $
##
#Y  Copyright (C) 2002, Lehrstuhl D fuer Mathematik, RWTH Aachen, Germany
##
##  mktest [-f] [-i] [-o] [-d] [-c]
##
##  This procedure runs an automatic test of all examples given in the CRYST
##  documentation files.
##
##  More precisely: Let 'file.tex' be one of these files. Then the test
##  function runs all examples given in that file and constructs (in the
##  current directory) a new version 'file.tst' of the given file which is
##  up-to-date with respect to the output of the examples.
##
##  The options have the following meaning:
##
##  If '-f' is specified run a full test (including the 'no test' examples if
##  there are any).
##
##  If '-i' is specified save the input file for the examples in a file
##  'file.in'.
##
##  If '-o' is specified save the output file of the examples in a file
##  'file.out'.
##
##  If '-d' is specified save the differences between the old and the new
##  manual file in a file 'file.dif'.
##
##  If '-d' and '-c' are specified use the context output format of the
##  'diff' command.
##

#############################################################################
##
##  Define the local call of the proper test function.
##
mktest="../../../../doc/test/mktest.sh"

#############################################################################
##
##  Get the options.
##
options=$*

#############################################################################
##
##  Run the test for all documentation files (in some arbitrary order).
##
$mktest $options introduction
$mktest $options -r cryst cryst
$mktest $options manual

