#!/bin/sh
#############################################################################
##
#W  doit							 Frank Celler
##
##  this shell script set the environment and then  calls to various programs
##  to extract the current  version, compile it, run  the test file, and  tar
##  everything up
##
. `dirname $0`/setvar

# checkout the new version
echo "======================================================================"
echo
if ${BINDIR}/checkout;  then echo;  else
    echo "PANIC: cannot checkout the next version"
    exit 1
fi


# compile the new version
echo
echo "======================================================================"
echo
if ${BINDIR}/compile;  then echo;  else
    echo "PANIC: cannot compile the next version"
    exit 1
fi


# run the test files the new version
echo
echo "======================================================================"
echo
if ${BINDIR}/readtest;  then echo;  else
    echo "PANIC: cannot run the test files"
    exit 1
fi


# tar the new version
echo
echo "======================================================================"
echo
if ${BINDIR}/tarit;  then echo;  else
    echo "PANIC: cannot tar the next version"
    exit 1
fi

echo
echo "======================================================================"
echo

echo $VERSION > ${ALPHAROOT}/VERSION

exit 0

