#!/bin/sh
#############################################################################
##
#W  setvar							 Frank Celler
##
##  this shell script sets the variables
##
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

# where does the CVS directory live
CVSROOT=:pserver:gap@cvs-gap.dcs.st-and.ac.uk:/gap/CVS


# where does the alpha directory live
ALPHAROOT=/usd/gap/4.alpha
if [ \! -d ${ALPHAROOT} ];  then
    echo "PANIC: directory '${ALPHAROOT}' does not exists"
    exit 1
fi


# executable
MAKETARGET=i386-ibm-freebsd-gcc2
GAPEXEC=${ALPHAROOT}/alpha/bin/i386-ibm-freebsd-gcc2/gap

# what is *this moment*
DATE=`date +"%D %T %Z"`


# what is the next version
if [ \! -f ${ALPHAROOT}/VERSION ];  then
    echo "PANIC: cannot find the version file '${ALPHAROOT}/VERSION'"
    exit 1
fi
OLD_VERSION=`cat ${ALPHAROOT}/VERSION`
if [ -z ${OLD_VERSION} ];  then
    echo "PANIC: version file '${ALPHAROOT}/VERSION' is corrupted'"
    exit 1
fi
VERSION=`expr ${OLD_VERSION} + 1`


# binary directory
BINDIR=${ALPHAROOT}/bin


# the tar directory
TARDIR=/usd/gap4


# export these variables
export CVSROOT ALPHAROOT VERSION BINDIR DATE GAPEXEC MAKETARGET TARDIR


