#!/bin/sh
# $Id: zooit,v 1.23 2004/05/02 14:16:19 gap Exp $
# Shell-Script to zoo the distribution of xgap
# This should be called right after the checkout and after making the
# documentation and html files without compiled versions in the current
# directory tree. It should be called from the GAP `pkg' directory.

# Change this for the latest revision:
# (Last digit is patchlevel) 
ZOOFILE=xgap4r21
ZOODOCFILE=xgapdoc4r21

rm -f TEXTCOM BINCOM
echo '!TEXT!' > TEXTCOM
echo '/END'   >>TEXTCOM
echo '!BINARY!'>BINCOM
echo '/END'   >>BINCOM

rm -f $ZOOFILE.zoo
rm -f $ZOODOCFILE.zoo

for i in xgap/{README,Makefile.in,configure,configure.in,init.g,PackageInfo.g}; do
  zoo ahc $ZOOFILE.zoo $i <TEXTCOM
done

for i in xgap/Changelog.* ; do
  zoo ahc $ZOOFILE.zoo $i <TEXTCOM
done

for i in xgap/xgap.shi ; do
  zoo ahc $ZOOFILE.zoo $i <TEXTCOM
done

for i in xgap/cnf/{M*,c*,i*}; do
  zoo ahc $ZOOFILE.zoo $i <TEXTCOM
done

for i in xgap/doc/{*.tex,*.msk,*.config,Makefile,manual.{six,bib,mst}}; do
  zoo ahc $ZOOFILE.zoo $i <TEXTCOM
done
for i in xgap/doc/manual.{dvi,pdf}; do
  zoo ahc $ZOOFILE.zoo $i <BINCOM
done
for i in xgap/doc/manual.six; do
  zoo ahc $ZOODOCFILE.zoo $i <TEXTCOM
done
for i in xgap/doc/manual.pdf; do
  zoo ahc $ZOODOCFILE.zoo $i <BINCOM
done

for i in xgap/examples/*; do
  zoo ahc $ZOOFILE.zoo $i <TEXTCOM
done

for i in xgap/htm/*; do
  zoo ahc $ZOOFILE.zoo $i <TEXTCOM
done
for i in xgap/htm/*; do
  zoo ahc $ZOODOCFILE.zoo $i <TEXTCOM
done

for i in xgap/lib/{*.g,*.gi,*.gd}; do
  zoo ahc $ZOOFILE.zoo $i <TEXTCOM
done

for i in xgap/src.x11/{*.c,*.h}; do
  zoo ahc $ZOOFILE.zoo $i <TEXTCOM
done

for i in xgap/src.x11/bitmaps/*; do
  zoo ahc $ZOOFILE.zoo $i <BINCOM
done

rm -f TEXTCOM BINCOM


