#!/bin/sh
#############################################################################
##
##  $Id$

if [ ${DISTROOT}X==X ]; then
  echo 'Loading environment settings'
  source ./setvar
fi

export GAPSOURCE=${DISTROOT}/gapsourcedistro

line='cd '${GAPSOURCE}
echo $line
$line 

pre=${DISTNAME}

echo 'Adding a list of text documentation files to '${GAPSOURCE}/listtextfiles.txt

find \
   $pre/doc/{ref,tut}/*.{txt,html,six,lab,toc,ind,css} \
       -print >> listtextfiles.txt

echo 'Adding a list of binary documentation files to '${GAPSOURCE}/listbinaryfiles.txt
             
find \
   $pre/doc/{ref,tut}/*.pdf \
       -print >> listbinaryfiles.txt
                         
exit 0
