#!/bin/sh
#############################################################################
##
##  $Id$

if [ ${DISTROOT}X==X ]; then
  echo 'Loading environment settings'
  source ./setvar
fi

export RELEASEBRANCH=${DISTROOT}/releasebranch

# create and go to build directory
if ! mkdir -p ${RELEASEBRANCH}; then
  echo 'Cannot create temporary directory '${RELEASEBRANCH}
  exit 1
fi

# copying ./setvar to the build directory for the meta-information archive

cp ./setvar ${RELEASEBRANCH}

echo 'Changing the directory to '${RELEASEBRANCH}
  
echo 'cd '${RELEASEBRANCH}
cd ${RELEASEBRANCH}
rm -rf ${DISTNAME}

# Checkout the files. Note that currently we do not use any tags.
echo "$0: checking out version $FULLVERSION of $DATE"
line='cvs -q -Q checkout '${GAPCVSVERSION}' -d '${DISTNAME}' 4.0'
echo $line
$line
if [ \! -d ${DISTNAME} ];  then
    echo "PANIC: cvs did not create a distribution directory"
    exit 1
fi

# What is *this moment*? If the subsequent wrapping and tests will be
# successful, recorded time of the checkout will be used to tag 
# corresponding revisions as included in the particular release.
export COREDATE=`date +"%d-%b-%Y"`
export CORETIME=`date -u +"%Y_%m_%d-%H_%M"`
export COREYEAR=`date +"%Y"`
echo "export CORETIME=\"$CORETIME\"" > core_checkout_time.txt
echo "export COREDATE=\"$COREDATE\"" >> core_checkout_time.txt
echo "export COREYEAR=\"$COREYEAR\"" >> core_checkout_time.txt

# logging the checked out state to a file
cd ${DISTNAME}
echo 'Logging the checkout state to '${RELEASEBRANCH}'/statuslog.txt'
cvs -q log -h -N > ../core_checkout_log.txt
cd ..
echo 'Logged the checkout state to '${RELEASEBRANCH}'/statuslog.txt'

# We do not use CVS later so we may erase .cvsignore files and CVS directories
echo 'Removing all .cvsignore files'
find ${DISTNAME} -name .cvsignore -exec rm -f {} ";"
echo 'Removing all CVS directories'
find -d ${DISTNAME} -name CVS -exec rm -rf {} ";"

# echo 'Removing development versions of packages'
# if needed leave packages which are required to be in a development version
# (see an example in commented out commands for 'tomlib').
# this should be adjusted simultaneosly with 'unpackpackages' script
#
# mv ${DISTNAME}/pkg/tomlib/ .
rm -rf ${DISTNAME}/pkg/*
# mv tomlib ${DISTNAME}/pkg/

# echo 'Adding packages needed to run GAP'

cd ${DISTNAME}/pkg/
echo 'Adding GAPDoc package'
wget -nv http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc/GAPDoc-1.3.tar.gz
gzip -dc GAPDoc-1.3.tar.gz | tar xp
rm GAPDoc-1.3.tar.gz

exit 0
