#!/bin/sh

#############################################################################
##
##  (C) Frank Lübeck
##  
##  Small utility for discovering potentially problematic file permissions.
##  Needs (GNU?)  'find'.
##  

if [ ${DISTROOT}X==X ]; then
  echo 'Loading environment settings'
  source ./setvar
fi

line='cd '${DISTROOT}/gapsourcedistro
echo $line
$line 

if [ `uname` = 'Darwin' ]
then
#############################################################################
#
# Trying Mac OS X find
#
echo "======================================================================"
echo "Directories not having 755 permissions:"
echo "trying Mac OS X find ..."
find . -type d -exec stat -f "%p %N" \{\} \; | grep -v "755"
echo "======================================================================"
echo "Files not having 644 or 755 permissions:"
echo "trying Mac OS X find ..."
find . -type f -exec stat -f "%p %N" \{\} \; | grep -v "644" | grep -v "755"
else
#############################################################################
#
# Trying GNU find
#
echo "======================================================================"
echo "Directories not having 755 permissions:"
echo "trying GNU find ..."
find . -type d -printf "%m %p\n" | grep -v "^755"
echo "======================================================================"
echo "Files not having 644 or 755 permissions:"
echo "trying GNU find ..."
find . -type f -printf "%m %p\n" | grep -v "^644" | grep -v "^755"
fi

#############################################################################
#
# The next block works in both systems
#
echo "======================================================================"
echo "Files with 755 permission, not recognized as executables by 'file':"
find . -type f -perm 755 -exec file \{\} \; | grep -v executable
echo "======================================================================"

exit 0
