#!/bin/sh
#############################################################################
##

if [ ${DISTROOT}X==X ]; then
  echo 'Loading environment settings'
  source ./setvar
fi

line='cd '${DISTROOT}'/gapsourcedistro/'${DISTNAME}''
echo $line
$line 

# build the documentation (to speed up things, without GMP)
./configure --with-gmp=no
make
make manuals
make clean

echo 'See the files '${DISTROOT}'/doc/tut/make_manuals.out and'
echo ${DISTROOT}'/doc/ref/make_manuals.out below for possible problems.'
echo '=========OUTPUT START:'${DISTROOT}'/doc/tut/make_manuals.out========='
cat doc/tut/make_manuals.out
echo '=========OUTPUT END:'${DISTROOT}'/doc/tut/make_manuals.out========='
echo '=========OUTPUT START:'${DISTROOT}'/doc/ref/make_manuals.out========='
cat doc/ref/make_manuals.out
echo '=========OUTPUT END:'${DISTROOT}'/doc/ref/make_manuals.out========='
echo 'See the files '${DISTROOT}'/doc/tut/make_manuals.out and'
echo ${DISTROOT}'/doc/ref/make_manuals.out above for possible problems.'

# fetch the `INSTALL' files from the manual
# grep -v "^%" ref/README.tex > ../README
# chmod go+r ../README

exit 0

