#!/bin/sh
#############################################################################
#
#
# Where to put the temporary export tree and archives. The path 
# "/mnt/raid/hudson-slave/..." is used by Jenkins continuous build system.
export DISTROOT=/mnt/raid/hudson-slave/workspace/GAP-update-release/wrap/gap45

# the Mercurial repository (access must be configured in advance)
export HGROOT="ssh://hg@hg.gap-system.org/gap"


# the version to wrap dependently on our needs:
# - to get the current snapshot of the named branch, use the name of 
#   the branch you need, e.g. "stable-4.5", "default" or "integration"
# - to get the state used for the previous release (e.g. to merge with 
#   the new packages archive, use corresponding tag, e.g. "v4.5.5" 
# export GAPHGVERSION="stable-4.5"
export GAPHGVERSION="v4.5.5"

# version to wrap
export VERSION="5"
export FULLVERSION="$VERSION.5"

# directory name
export DISTNAME="gap4r$VERSION"

# archive name
export RBVERSION="4r5p5"
export ARCHNAME="gap$RBVERSION"

# location of the merged packages archive (assumed to be on the same machine)
export MERGEDPKGLOC="/mnt/raid/hudson-slave/workspace/GAP-pkg-update/pkgadmin/mergedarchives"

#-----------------------------------------------------------------------------
# everything below should be system independent.

# unset locale settings
export LANG="C"
export LC_ALL="C"

umask 022

echo "*** Environment set for creating Version GAP 4."${FULLVERSION}
