#!/bin/sh -ex
#############################################################################
##
##
## Updates version number and release date. 
## The following information should be changed for *every* release:
## 1) lib/system.g: 'Version' and 'Date' in lines
##    Version := "4.dev",
##    Date := "today",
##    NeedKernelVersion := "4.dev",
## 2) src/system.c: 'SyKernelVersion' in line
##    const Char * SyKernelVersion = "4.dev";
##                  'SyWindowsPath' in line
##    const Char * SyWindowsPath = "/cygdrive/c/gap4dev";
## 3) doc/versiondata: 'VERSIONNUMBER', 'VERSIONSUFFIX', 'RELEASEDAY', 
##    'RELEASEYEAR' in lines
##  <!ENTITY VERSIONNUMBER "4.dev">
##  <!ENTITY VERSIONSUFFIX "4r5dev">
##  <!ENTITY RELEASEDAY "today">
##  <!ENTITY RELEASEYEAR "this year">


if [ ${DISTROOT}X==X ]; then
  echo 'Loading environment settings'
  source ./setvar
fi

line='cd '${DISTROOT}/gapcore
echo $line
$line 

source ./core_checkout_time.txt

cd ${DISTNAME}
sed -i -e "s/4.dev/4.$FULLVERSION/g" CITATION
sed -i -e "s/this year/$COREYEAR/g" CITATION

cd lib/
sed -i -e "s/4.dev/4.$FULLVERSION/g" system.g
sed -i -e "s/today/$COREDATE/g" system.g

cd ../src/
sed -i -e "s/4.dev/4.$FULLVERSION/g" system.c
sed -i -e "s/gap4dev/$DISTNAME/g" system.c

cd ../doc/
sed -i -e "s/4.dev/4.$FULLVERSION/g" versiondata
sed -i -e "s/today/$COREDATE/g" versiondata
sed -i -e "s/this year/$COREYEAR/g" versiondata
sed -i -e "s/gap4dev/$DISTNAME/g" versiondata

cd ../cnf/
sed -i -e "s/4.dev/4.$FULLVERSION/g" configure.in
sed -i -e "s/4.dev/4.$FULLVERSION/g" configure.out

cd ../bin/
sed -i -e "s/gap4dev/$DISTNAME/g" gap.bat
sed -i -e "s/gap4dev/$DISTNAME/g" gapcmd.bat
sed -i -e "s/gap4dev/$DISTNAME/g" gaprxvt.bat

cd ..

exit 0
