#!/bin/sh
#############################################################################
##
##  $Id$

if [ ${DISTROOT}X==X ]; then
  echo 'Loading environment settings'
  source ./setvar
fi

export GAPCORE=${DISTROOT}/gapcore

line='cd '${GAPCORE}
echo $line
$line 

source ./core_checkout_time.txt

pre=${DISTNAME}
metainfoarchive=metainfo${ARCHNAME}_core${CORETIME}.zip
rm -f $metainfoarchive

echo 'Adding meta-information to '${GAPCORE}/$metainfoarchive

find \
   ./setvar \
   ./core_checkout_*.txt \
   ./list* \
       -print | zip -q ${metainfoarchive} -@

exit 0
