#!/bin/sh
#############################################################################
##

if [ ${DISTROOT}X==X ]; then
  echo 'Loading environment settings'
  source ./setvar
fi

export GAPSOURCE=${DISTROOT}/gapsourcedistro

line='cd '${GAPSOURCE}
echo $line
$line 

source ./core_checkout_time.txt

ziparchive=${ARCHNAME}_${CORETIME}.zip
winziparchive=${ARCHNAME}_${CORETIME}-win.zip
rm -f $ziparchive
rm -f $winziparchive

echo '===================================================================='
echo 'Wrapping archive '${GAPSOURCE}/$ziparchive
echo 'Adding text files to '${GAPSOURCE}/$ziparchive
cat listtextfiles.txt | zip -q -9 ${ziparchive} -@
echo 'Adding binary files to '${GAPSOURCE}/$ziparchive
cat listbinaryfiles.txt | zip -q -9 ${ziparchive} -@

echo '===================================================================='
echo 'Wrapping archive '${GAPSOURCE}/$winziparchive
echo 'Adding text files to '${GAPSOURCE}/$winziparchive
cat listtextfiles.txt | zip -q -9 -l ${winziparchive} -@
echo 'Adding binary files to '${GAPSOURCE}/$winziparchive
cat listbinaryfiles.txt | zip -q -9 ${winziparchive} -@

echo '===================================================================='
echo 'Unpacking .zip archive to check for missing files ...'
unzip -q ${ziparchive} -d tmpunpack
mv tmpunpack/${DISTNAME} ${DISTNAME}tst
rm -rf tmpunpack
diff -rq ${DISTNAME} ${DISTNAME}tst
rm -rf ${DISTNAME}tst
             
exit 0