#!/bin/sh -ex
#############################################################################
##

if [ ${DISTROOT}X==X ]; then
  echo 'Loading environment settings'
  source ./setvar
fi

export RELEASEBRANCH=${DISTROOT}/releasebranch

line='cd '${RELEASEBRANCH}
echo $line
$line 

source ./core_checkout_time.txt

pre=${DISTNAME}
metainfoarchive=metainfo${ARCHNAME}_release_branch${CORETIME}.zip
rm -f $metainfoarchive

echo 'Adding meta-information to '${RELEASEBRANCH}/$metainfoarchive

find \
   ./setvar \
   ./core_checkout_*.txt \
   ./list* \
       -print | zip -q ${metainfoarchive} -@

exit 0
