#!/bin/sh
#############################################################################
##
##  $Id$

if [ ${DISTROOT}X==X ]; then
  echo 'Loading environment settings'
  source ./setvar
fi

export RELEASEBRANCH=${DISTROOT}/releasebranch

line='cd '${RELEASEBRANCH}
echo $line
$line 

source ./core_checkout_time.txt

ziparchive=${ARCHNAME}_release_branch${CORETIME}.zip
toolsarchive=tools${ARCHNAME}_release_branch${CORETIME}.zip
# we clean previous attempts to wrap the same checkout
rm -f ${ziparchive}
rm -f ${toolsarchive}

echo 'Adding text files to the archive '${RELEASEBRANCH}/$ziparchive
cat listtextfiles.txt | zip -q ${ziparchive} -@

echo 'Adding binary files to the archive '${RELEASEBRANCH}/$ziparchive
cat listbinaryfiles.txt | zip -q ${ziparchive} -@
             
echo 'Adding text tools files to the archive '${RELEASEBRANCH}/$toolsarchive
cat listtextfilesfortools.txt | zip -q ${toolsarchive} -@

# uncomment the next block if there will be any binary files for tools
# echo 'Adding binary tools files to the archive '${RELEASEBRANCH}/$toolsarchive
# cat listbinaryfilesfortools.txt | zip -q ${toolsarchive} -@

exit 0
