#!/bin/sh
#############################################################################
##
#W  mktest         Test the ResClasses manual examples         Volkmar Felsch
##
#H  $Id: mktest,v 1.5 2006/05/29 11:44:07 stefan Exp $
##
#Y  Copyright (C) 2002, Lehrstuhl D fuer Mathematik, RWTH Aachen, Germany
##
##  mktest [-f] [-i] [-o] [-d] [-c]
##
##  This procedure runs an automatic test of all examples given in the RCWA
##  documentation files.
##
##  More precisely: Let 'file.xml' be one of these files. Then the test
##  function runs all examples given in that file and constructs (in the
##  current directory) a new version 'file.xtst' of the given file which is
##  up-to-date with respect to the output of the examples.
##
##  The options have the following meaning:
##
##  If '-f' is specified run a full test (including the 'no test' examples if
##  there are any).
##
##  If '-i' is specified save the input file for the examples in a file
##  'file.in'.
##
##  If '-o' is specified save the output file of the examples in a file
##  'file.out'.
##
##  If '-d' is specified save the differences between the old and the new
##  manual file in a file 'file.dif'.
##
##  If '-d' and '-c' are specified use the context output format of the
##  'diff' command.
##

#############################################################################
##
##  Define the local call of the proper test function.
##
mkxtest="../../../../doc/test/mkxtest.sh"

#############################################################################
##
##  Get the options.
##
options=$*

#############################################################################
##
##  Run the test for all documentation files (in some arbitrary order).
##
$mkxtest $options -r resclasses resclass
$mkxtest $options -r resclasses fixedrep
$mkxtest $options -r resclasses z_pi
$mkxtest $options -r resclasses resclaux

