#!/bin/sh
# $Id$    (C) Frank Lübeckk 

mypath=`dirname  $0`/

source ${mypath}setup

cd ${PkgWebFtpDir}/ftpdir

echo "Dry run:"
rsync -av -c -n tar.gz tar.bz2 zoo win.zip  ${FtpServer}
read -n 1 -p "Shall I copy? (y/n)> " ANSWER
echo

if [ $ANSWER = "y" ]; then
  echo "Ok, I'll copy ..."
  rsync -av -c  tar.gz tar.bz2 zoo win.zip  ${FtpServer}
else
  echo "Don't copy, bye."
fi

