#!/bin/sh
#(C) Bjoern 
# Example of usage:
# 1. Go to pkg cache directory 
#    (for example:   cd ~/PackageAdmin/pkgcache/crime ).
# 2  Call the script with the archive name that you want to copy.
#    Note that you should only specify the name body and not the ending
#    (for example:   copyArchivesOfBadPkg2Webftp crime-0.2 ).
#
source ~/PackageAdmin/PackageAdmin/setup

rsync $1.tar.gz ${PkgWebFtpDir}/ftpdir/tar.gz/packages/ 
rsync $1.tar.bz2 ${PkgWebFtpDir}/ftpdir/tar.bz2/packages/ 
rsync $1-win.zip ${PkgWebFtpDir}/ftpdir/win.zip/packages/ 
rsync $1.zoo ${PkgWebFtpDir}/ftpdir/zoo/packages/ 
