#!/bin/sh
# $Id: updatePackageInfoFiles,v 1.1 2004/07/14 13:17:04 gap Exp $    (C) Frank Lübeck


mypath=`dirname  $0`/

source ${mypath}setup

$GAP -r -b -q  ${mypath}PackageInfoTools.g  << EOI
ANSI_COLORS := false;;
Unbind(PrintPromptHook);
Print("\n");


newinfo := UpdatePackageInfoFiles("${PkgCacheDir}");;
if Length(newinfo) > 0 then
  Print("\nPackages with changes PackageInfo.g files:\n", newinfo, "\n");
else
  Print("\nNo changed PackageInfo.g files!\n");
fi;

quit;
EOI

