#!/bin/sh
# $Id: updatePackageDocs,v 1.1 2004/07/14 13:17:04 gap Exp $    (C) Frank Lübeck


mypath=`dirname  $0`/

source ${mypath}setup

$GAP -r -b -q  ${mypath}PackageInfoTools.g  << EOI
ANSI_COLORS := false;;
Unbind(PrintPromptHook);
Print("\n");


newdocs := UpdatePackageDoc("${PkgCacheDir}", "${PkgWebFtpDir}/Packages/pkg");;
if Length(newdocs) > 0 then
  Print("\nPackages with updated online manual books:\n", newdocs, "\n");
else
  Print("\nAll online manual books are up to date!\n");
fi;

quit;
EOI

