#!/bin/sh
# $Id$    (C) Frank Lübeck


mypath=`dirname  $0`/

source ${mypath}setup

$GAP -r -b -q  ${mypath}PackageInfoTools.g  << EOI
ANSI_COLORS := false;;
Unbind(PrintPromptHook);
Print("\n");


newinfo := UpdatePackageInfoFiles("${PkgCacheDir}");;
if Length(newinfo) > 0 then
  Print("\nPackages with changes PackageInfo.g files:\n", newinfo, "\n");
else
  Print("\nNo changed PackageInfo.g files!\n");
fi;

quit;
EOI

