#!/bin/sh
# $Id: updatePackageArchives,v 1.1 2004/07/14 13:17:04 gap Exp $    (C) Frank Lübeck


mypath=`dirname  $0`/

source ${mypath}setup

$GAP -r -b -q  ${mypath}PackageInfoTools.g  << EOI
ANSI_COLORS := false;;
Unbind(PrintPromptHook);
Print("\n");


newarchs := UpdatePackageArchives("${PkgCacheDir}", "${PkgWebFtpDir}");;
if Length(newarchs) > 0 then
  Print("\nPackages with new archive files:\n", newarchs, "\n");
else
  Print("\nNo new package archive  files!\n");
fi;

quit;
EOI

