#!/bin/sh

echo This is only for zooing packages for Unix installations
echo 
echo zooing $1
echo
cvs -d /gap/CVS export -D today 4.0/pkg/$1 > /dev/null 2>&1
cd 4.0/pkg
find . -type f \! -name .cvsignore -exec zoo ah ../../$1.zoo {} \; > /dev/null 2>&1
cd ../..
echo result should be in $1.zoo

