#!/bin/bash
# this script collects the i686 and x86_64 installations into one
# directory for the rsync server

export Orig_i686=gemma:/export3/home/tmp/gap4412/gap4r4
export Orig_x86_64=/home3/beteigeuze/tmp/gap4412/gap4r4

export DEST=/home2/beteigeuze/luebeck/GAPrsync/gap4


echo collecting in $DEST . . .
mkdir -p $DEST
cd $DEST

# in this order we get Makefile's and so on from i686 architecture
# (first with --delete like starting from scratch, but second without!)
echo syncing x86_64 version from $Orig_x86_64
rsync -c -av --delete $Orig_x86_64 .
echo syncing i686 version from $Orig_i686
rsync -c -av $Orig_i686 .


