#!/usr/bin/tcsh

# $Id$

# You need 'gzip', GNU 'tar', a C compiler, sed, pdftex to run this.
# And the files: gap4r4.tar.gz, packages-XXX.tar.gz, tools4r4.tar.gz,
#                xtom1r1.tar.gz

# Frank Lübeck, Frank.Luebeck@Math.RWTH-Aachen.De for questions and complaints.

# Note, that this isn't and is not intended to be a sophisticated script.
# Even if it doesn't work completely automatically for you, you may get 
# an idea what to do for a complete installation of GAP.


setenv NAME "4r4"

# adjust settings as you like, the example is  for gcc under Linux ix86
# (use settings like "-v8a -fast" or "-v9a -fast" for 32bit or 64bit
# compilations with SUN's compilers under Solaris, and similar for other
# systems)
setenv COPTS "-Wall -O2 -g -fomit-frame-pointer -pipe -mpreferred-stack-boundary=2 -march=i686 -fno-strict-aliasing"

# you can also set this to choose a C compiler
#setenv CC ...

# and you can fix extra linker options, e.g.,
setenv LOPTS "-static"

tar xzvf gap$NAME.tar.gz
tar xzvf tools$NAME.tar.gz
tar xzvf xtom1r1.tar.gz
cd gap$NAME/pkg
tar xzvf ../../packages-*.tar.gz

cd ..

# compile GAP
./configure
make
#unsetenv COPTS
#unsetenv LOPTS
# we collect all start scripts in 'bin'
cp bin/`sed -e 's/GAParch=//' sysinfo.gap`/gac bin

# now the packages
cd pkg

#cd ace
#./configure ../..
#make
#cd ..

#cd anupq
#./configure ../..
# on Linux with gmp in standard place and with GAP 4.3 gap.sh script
# in standard path as: gap  just do: make  (otherwise check installation
# instructions - configure output gives hints)
#make
#cd ..

# You may not want a writable directory here! In this case substitute
# the directories 'datagens' and 'dataword' by links to somewhere else.
cd atlasrep
chmod 1777 datagens dataword
cd ..

# This produces a lot of data, maybe you want to leave this out until a user
# complains.
cd carat
tar xzf carat*.tar.gz
ln -s carat/bin bin
cd carat
mv Makefile Makefile.orig
echo 'TOPDIR = '`pwd` > Makefile
echo 'CFLAGS='$COPTS >> Makefile
grep -v "^\(TOPDIR\|CFLAGS\|CC\)" Makefile.orig >> Makefile
make
cd ../..

cd cohomolo
make clean
./configure 
cd standalone/progs.d
mv makefile makefile.orig
echo 'CFLAGS='$COPTS' -static' > makefile
grep -v "^\(CFLAGS\)" makefile.orig >> makefile
cd ../..
make 
cd ..

# create dynamic library and statically linked GAP with EDIM kernel module
cd edim
make clean
unsetenv LANG
unsetenv LC_ALL
./configure
make
cd ../../bin/`sed -e 's/GAParch=//' ../../sysinfo.gap`
./gac -o gap -P "-static" -p "-DEDIVSTATIC " ../../pkg/edim/src/ediv.c
cd ../../pkg

cd example
./configure ../..
make
cd ..

#cd fplsa
#./configure ../..
#make
#cd doc
#tex manual
#tex manual
#cd ../..

cd grape
./configure ../..
make linux-gcc
cd ..

#cd guava182
#./configure ../..
#make
#cd ..

cd kbmag
make clean
./configure ../..
make COPTS="-O2 -g -static"
cd ..

#  see the pargap documentation how to use this 
#  (in particular, user needs procgroup file)
#cd pargap
#./configure ../..
#make
#cp bin/pargap.sh ../../bin/
#cd ..

# For XGap the following shared libraries of the X window system must be 
# installed on your machine together with the development files (header 
# files and so on):
# 
#   libXaw.so, libXmu.so, libXt.so, libXext.so, libX11.so, libSM.so, libICE.so
# 
# In addition you need on XFree Version >= 4:
# 
#   libXpm.so
#
# If you  miss one of  these under Linux you  can usually just  install some
# more packages of your favorite distribution. The development files usually
# come in some package with "dev" in its name.
#cd xgap
#./configure
#make
#cp bin/xgap.sh ../../bin/
#cd ..



