#!/bin/sh 
#usage: testexample <skeletonfile> [<gap-options>]  [-quiet]
awk -f getinput.awk $1
if [ "x$2" = "x-quiet" ]; then
      gapopts=$3
      quiet=1
elif [ "x$3" = "x-quiet" ]; then
      gapopts="$2"
      quiet=1
else
      gapopts="$2"
      quiet=0
fi
../../bin/gap.sh -b -A -T $gapopts <in > /dev/null
awk -f parseoutput.awk -v quiet=$quiet gaout 
