name: CI with GAP.jl

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'master'
      - 'stable-*'

concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the default repository branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref_name != github.event.repository.default_branch || github.run_number }}
  # Cancel intermediate builds, but only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: Julia ${{ matrix.julia-version }} - GAP.jl ${{ matrix.gapjl-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 40
    continue-on-error: ${{ matrix.julia-version == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        gapjl-version:
          - 'latest-release'
          - 'master'
        julia-version:
          - '1.10'
          - '1'         # latest stable release
          - 'nightly'
        os:
          - ubuntu-latest
        include:
          # Add a few macOS jobs (the number we can run in parallel is limited)
          - gapjl-version: 'latest-release'
            julia-version: '1'
            os: macOS-latest
          - gapjl-version: 'master'
            julia-version: '1'
            os: macOS-latest

    steps:
      - name: Checkout GAP
        uses: actions/checkout@v7
        with:
          path: 'GAPROOT'
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.julia-version }}
      - name: Install GAP.jl
        shell: julia --color=yes {0}
        run: |
          using Pkg
          if "${{ matrix.gapjl-version }}" == "latest-release"
            Pkg.develop("GAP")
          else
            Pkg.add(;name="GAP", rev="${{ matrix.gapjl-version }}")
          end
          path = dirname(dirname(Base.find_package("GAP")))
          open(ENV["GITHUB_ENV"], "a") do io
              println(io, "GAPJLPATH=$path")
          end
      - name: "Install dependencies (for macOS)"
        if: runner.os == 'macOS'
        run: |
          # - autoconf, gmp, zlib are needed by GAP's build system
          # - coreutils provides nproc
          # - force use of Homebrew gcc to build GAP for proper stacktrace support
          #   Homebrew installs versioned binaries such as gcc-14 and g++-14,
          #   while later scripts expect unversioned gcc and g++ in PATH.
          brew install autoconf gmp zlib gcc@14 coreutils

          # ensure gcc and g++ are available under those names (on macOS,
          # these names are aliases for clang / clang++ out of the box)
          shimdir="${HOME}/bin"
          mkdir -p "${shimdir}"
          ln -sf "$(brew --prefix)/bin/gcc-14" "${shimdir}/gcc"
          ln -sf "$(brew --prefix)/bin/g++-14" "${shimdir}/g++"
          echo "${shimdir}" >> "${GITHUB_PATH}"
      - name: "Build GAP"
        run: |
          mv GAPROOT /tmp/GAPROOT
          cd /tmp/GAPROOT
          patchdir=$GAPJLPATH/.github/workflows/GAP_patches/master
          if [ -d $patchdir ]; then
            for f in $patchdir/*.patch; do
              echo "Applying patch ${f}"
              patch -p1 -d . < ${f}
            done
          fi
          ./autogen.sh
          ./configure --enable-Werror
          make -j`nproc`
      - name: "Override bundled GAP"
        run: |
          julia --project=$GAPJLPATH $GAPJLPATH/etc/setup_override_dir.jl /tmp/GAPROOT /tmp/gap_jll_override --enable-Werror
      - name: "Run tests"
        run: |
          julia --project=$GAPJLPATH $GAPJLPATH/etc/run_with_override.jl /tmp/gap_jll_override --depwarn=error -e "using Pkg; Pkg.test(\"GAP\")"
