#!/bin/sh
#############################################################################
##
#W  mkdiff      Differences of examples (package manual)       Volkmar Felsch
##
#H  $Id: mkdiff,v 1.1 2002/10/11 14:44:50 gap Exp $
##
#Y  Copyright (C) 2002, Lehrstuhl D fuer Mathematik, RWTH Aachen, Germany
##
##  mkdiff.sh [-c] [file1 file2 ...]
##
##  This is the 'mkdiff' version for XML files of package documentations.
##
##  For each file name 'file', say, in the given list of file names compare
##  the manual file '../file.tex' with the test file 'file.tst' and write all
##  differences to a file 'xdiffs'.
##
##  If '-c' is specified use the context output format of the 'diff' command.
##
##  If no file names are specified handle all '.tst' files in the current
##  directory.
##

#############################################################################
##
##  Define the local call of the proper test function.
##
mkxdiff="../../../../doc/test/mkxdiff.sh"


#############################################################################
##
##  Run the test for each of the documentation files.
##
$mkxdiff $*

